import { describe, expect, test } from "vitest"
import vectors from "../../../reference/key-model-v2/vectors.json"
import { deriveBip39Seed, deriveMasterFromMnemonic } from "./mnemonic-master"

/**
 * KATs for the BIP-39 step of NULO-ACCOUNT-KDF v2. The reference values were generated by
 * node:crypto's PBKDF2 (a different implementation than this module's WebCrypto) in
 * `reference/key-model-v2/derive-vectors.ts`; the TREZOR-passphrase rows
 * additionally carry the official published BIP-39 seeds, recomputation-verified by the
 * generator. Never re-pin from this implementation.
 */
const toHex = (bytes: Uint8Array): string => Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("")

describe("deriveBip39Seed — official + reference KATs", () => {
	for (const row of vectors.bip39) {
		test(`official TREZOR seed for entropy ${row.entropy.slice(0, 8)}…`, async () => {
			expect(toHex(await deriveBip39Seed(row.sentence.split(" "), "TREZOR"))).toBe(row.seedTrezor)
		})
		test(`empty-passphrase (production) seed for entropy ${row.entropy.slice(0, 8)}…`, async () => {
			expect(toHex(await deriveBip39Seed(row.sentence.split(" ")))).toBe(row.seedEmptyPassphrase)
		})
	}

	test("unicode passphrase is NFKD-normalized (U+FB01 ligature row)", async () => {
		const { sentence, passphrase, seed } = vectors.unicodePassphrase
		expect(toHex(await deriveBip39Seed(sentence.split(" "), passphrase))).toBe(seed)
	})

	test("canonicalization: case, padding, and repeated whitespace do not change the seed", async () => {
		const messy = `  ${vectors.bip39[0]!.sentence.toUpperCase().replace(/ /g, "   ")} `
		expect(toHex(await deriveBip39Seed(messy.split(" ")))).toBe(vectors.bip39[0]!.seedEmptyPassphrase)
	})
})

describe("deriveMasterFromMnemonic — seed64 → Fr master", () => {
	test("all-zeros-entropy words reduce to the reference master", async () => {
		const master = await deriveMasterFromMnemonic(vectors.fullChain.sentence.split(" "))
		expect(`0x${toHex(master)}`).toBe(vectors.fullChain.master)
		expect(master.byteLength).toBe(32)
	})
})
