<!-- Modified from Azguard Wallet (https://github.com/AzguardWallet/azguard-wallet), Copyright 2026 BB Strategy Pte. Ltd., Apache-2.0. -->
<script setup>
import PasswordVisibilityToggle from "@/components/composite/PasswordVisibilityToggle.vue"
import { newPasswordHint } from "@/utils/password"
/**
 * Section labels carry the visual heading; individual Inputs run
 * label-less to avoid duplicating the heading text. Hints (strength,
 * "Correct" indicator) move under each input via the #bottom slot so
 * they share the same below-input rail the error rail uses.
 */
const props = defineProps({
	method: { type: String, required: true }, // 'seed'
	error: { type: Object, default: () => ({ type: "", title: "", tooltip: "" }) },
	maxPasswordLength: { type: Number, default: 128 },
})

const emit = defineEmits(["secretInput", "passwordInput"])

const seedPhrase = defineModel("seedPhrase", { default: undefined })
const password = defineModel("password", { default: "" })
const repeatedPassword = defineModel("repeatedPassword", { default: "" })

const isPasswordType = ref(true)
const hideCredentials = ref(true)

const passwordHint = computed(() => newPasswordHint(password.value ?? "", repeatedPassword.value ?? ""))
</script>

<template>
	<div :class="$style.section">
		<span :class="$style.section_label">Recovery Phrase</span>
		<span :class="$style.note" data-testid="import-seed-note">
			24 words separated by spaces. Use a phrase generated by Nulo. A phrase shared with another wallet lets that software derive your keys.
		</span>

		<Input
			v-if="method === 'seed'"
			v-model="seedPhrase"
			data-testid="import-seed-input"
			@input="emit('secretInput')"
			:type="hideCredentials ? 'password' : 'text'"
			placeholder="Enter recovery phrase"
			autocomplete="off"
		>
			<template #suffix>
				<PasswordVisibilityToggle
					:hidden="hideCredentials"
					subject="recovery phrase"
					data-testid="import-seed-input-visibility-toggle"
					@toggle="hideCredentials = !hideCredentials"
				/>
			</template>
			<template v-if="seedPhrase?.split(' ').length === 24" #bottom>
				<Flex align="center" gap="4" :class="$style.hint_row">
					<Icon name="check-circle" size="12" color="green" />
					<Text size="12" weight="600" color="primary">Correct</Text>
				</Flex>
			</template>
		</Input>
	</div>

	<div :class="$style.section_last">
		<span :class="$style.section_label">New Password</span>
		<Flex direction="column" gap="12">
			<Input
				v-model="password"
				data-testid="import-password-input"
				:type="isPasswordType ? 'password' : 'text'"
				@input="emit('passwordInput')"
				:maxLength="maxPasswordLength"
				placeholder="Enter new password"
				autocomplete="new-password"
			>
				<template #suffix>
					<PasswordVisibilityToggle
						:hidden="isPasswordType"
						data-testid="import-password-input-visibility-toggle"
						@toggle="isPasswordType = !isPasswordType"
					/>
				</template>
				<template #bottom>
					<Flex align="center" gap="6" :class="$style.hint_row">
						<MaterialIcon name="lock" :size="12" color="tertiary" />
						<Text size="12" weight="600" color="tertiary">{{ passwordHint }}</Text>
					</Flex>
				</template>
			</Input>
			<Input
				v-model="repeatedPassword"
				data-testid="import-password-confirm-input"
				:type="isPasswordType ? 'password' : 'text'"
				@input="emit('passwordInput')"
				:maxLength="maxPasswordLength"
				placeholder="Repeat password"
				autocomplete="new-password"
			/>
		</Flex>

		<Flex v-if="error.type === 'unknown'" align="center" gap="8" :class="$style.unknown_error">
			<span :class="$style.error_tag">Error</span>
			<Text size="12" weight="600" color="secondary">{{ error.title }}</Text>
		</Flex>
	</div>
</template>

<style module>
/* No section-level border-bottom: each section's last child is an Input
 * whose `.base { border-bottom }` already underlines the section. The
 * extra divider produced two 1px lines stacked ~20px apart. */
.section {
	/* Declared, not composed: Vite copies a composed file into every module that composes it, so a
	 * `gap` override here would win or lose against another module's copy on bundle order. */
	display: flex;
	flex-direction: column;
	gap: 8px;
	padding: 20px 0;
}

.section_last {
	composes: section_last from "./import-shared.module.css";
}

.section_label {
	composes: section_label from "./import-shared.module.css";
}

.note {
	font-size: 12px;
	font-weight: 500;
	line-height: 1.35;
	color: var(--txt-tertiary);
}

.hint_row {
	margin-top: 4px;
}

.unknown_error {
	margin-top: 12px;
}

.error_tag {
	font-family: var(--font-headline);
	font-size: 10px;
	font-weight: 700;
	letter-spacing: 0.2em;
	text-transform: uppercase;
	color: var(--red);
	border: 1px solid var(--red);
	padding: 2px 6px;
	flex-shrink: 0;
}
</style>
