import { Flex, Icon, Input, MaterialIcon, Text } from "@nulo/design"
import { mount, type VueWrapper } from "@vue/test-utils"
import { afterEach, describe, expect, it } from "vitest"
import { expectMaskToggle, expectNativeAttrs, nativeInput, pasteInto } from "../../../../tests/helpers/credential-pins"
import ImportSecretForm from "./ImportSecretForm.vue"

const stubs = {
	Flex: { template: "<div><slot /></div>" },
	Text: { template: "<span><slot /></span>" },
	Icon: { props: ["name"], template: '<i :data-name="name"></i>' },
	MaterialIcon: { template: "<i></i>" },
	Tooltip: { template: "<div data-tooltip><slot /><slot name='content' /></div>" },
	Transition: { template: "<div><slot /></div>" },
	Input: {
		props: ["modelValue", "label", "placeholder", "type", "error", "maxLength"],
		emits: ["update:modelValue", "input"],
		template: `<input
				:data-testid="$attrs['data-testid']"
				:value="modelValue"
				:type="type"
				:data-error="error"
				@input="$emit('update:modelValue', $event.target.value); $emit('input', $event)"
			/><slot name='right' /><slot name='suffix' /><slot name='labelSuffix' /><slot name='bottom' />`,
	},
}

const baseProps = (over = {}) => ({
	method: "seed",
	error: { type: "", title: "", tooltip: "" },
	maxPasswordLength: 128,
	...over,
})

describe("ImportSecretForm", () => {
	it("renders phrase input + new+confirm password fields when method=seed", () => {
		const wrapper = mount(ImportSecretForm, { props: baseProps(), global: { stubs } })
		expect(wrapper.text()).toContain("Recovery Phrase")
		expect(wrapper.text()).toContain("New Password")
		// new + confirm
		expect(wrapper.find("[data-testid=import-password-input]").exists()).toBe(true)
		expect(wrapper.find("[data-testid=import-password-confirm-input]").exists()).toBe(true)
	})

	it("exposes ONLY the seed input testid (plain/encrypted key inputs are gone)", () => {
		const seed = mount(ImportSecretForm, { props: baseProps({ method: "seed" }), global: { stubs } })
		expect(seed.find("[data-testid=import-seed-input]").exists()).toBe(true)
		expect(seed.find("[data-testid=import-private-key-input]").exists()).toBe(false)
		expect(seed.find("[data-testid=import-public-key-input]").exists()).toBe(false)
	})

	it("emits secretInput when typing into the phrase field", async () => {
		const wrapper = mount(ImportSecretForm, { props: baseProps({ method: "seed" }), global: { stubs } })
		await wrapper.find("[data-testid=import-seed-input]").trigger("input")
		expect(wrapper.emitted("secretInput")).toBeTruthy()
	})

	it("emits passwordInput when typing into the password field", async () => {
		const wrapper = mount(ImportSecretForm, { props: baseProps(), global: { stubs } })
		await wrapper.find("[data-testid=import-password-input]").trigger("input")
		expect(wrapper.emitted("passwordInput")).toBeTruthy()
	})

	it("shows the unknown-error banner when error.type === 'unknown'", () => {
		const wrapper = mount(ImportSecretForm, {
			props: baseProps({ error: { type: "unknown", title: "Boom", tooltip: "" } }),
			global: { stubs },
		})
		expect(wrapper.text()).toContain("Error")
		expect(wrapper.text()).toContain("Boom")
	})

	it("states the recovery-phrase note as text between the label and the field, with no ⓘ", () => {
		const wrapper = mount(ImportSecretForm, { props: baseProps({ method: "seed" }), global: { stubs } })
		const note = wrapper.get("[data-testid=import-seed-note]")
		expect(note.text()).toBe(
			"24 words separated by spaces. Use a phrase generated by Nulo. A phrase shared with another wallet lets that software derive your keys.",
		)
		const section = note.element.parentElement
		expect(section?.firstElementChild?.textContent).toBe("Recovery Phrase")
		expect(section?.firstElementChild?.nextElementSibling).toBe(note.element)
		expect(note.element.nextElementSibling).toBe(wrapper.get("[data-testid=import-seed-input]").element)
		expect(wrapper.find("[data-tooltip]").exists()).toBe(false)
		expect(wrapper.find('[data-name="info"]').exists()).toBe(false)
	})

	it("shows the 'Correct' indicator only at exactly 24 words", () => {
		const short = mount(ImportSecretForm, { props: baseProps({ method: "seed" }), global: { stubs } })
		expect(short.text()).not.toContain("Correct")
		const full = mount(ImportSecretForm, {
			props: { ...baseProps({ method: "seed" }), seedPhrase: Array(24).fill("word").join(" ") },
			global: { stubs },
		})
		expect(full.text()).toContain("Correct")
	})
})

describe("ImportSecretForm — credential controls, real Input", () => {
	const mounted: VueWrapper[] = []
	afterEach(() => {
		for (const w of mounted.splice(0)) w.unmount()
	})
	const mountReal = () => {
		const w = mount(ImportSecretForm, {
			props: baseProps(),
			attachTo: document.body,
			global: { components: { Flex, Icon, Input, MaterialIcon, Text } },
		})
		mounted.push(w)
		return w
	}
	const SEED = "import-seed-input"
	const PAIR = ["import-password-input", "import-password-confirm-input"]

	it("the phrase toggle masks the phrase alone", async () => {
		await expectMaskToggle(mountReal(), {
			toggle: "import-seed-input-visibility-toggle",
			field: SEED,
			drives: [SEED],
			others: PAIR,
			subject: "recovery phrase",
		})
	})

	it("the password toggle masks both password fields and never the phrase", async () => {
		await expectMaskToggle(mountReal(), {
			toggle: "import-password-input-visibility-toggle",
			field: PAIR[0],
			drives: PAIR,
			others: [SEED],
		})
	})

	it("native attributes per field, and nothing is focused on mount", () => {
		const w = mountReal()
		expectNativeAttrs(w, SEED, { autocomplete: "off", autocapitalize: null, autocorrect: null })
		for (const id of PAIR) expectNativeAttrs(w, id, { autocomplete: "new-password", autocapitalize: null, autocorrect: null })
		expect(document.activeElement).toBe(document.body)
	})

	it("a paste into the phrase is native; a paste into a password field is capped at 128", () => {
		const w = mountReal()
		expect(pasteInto(nativeInput(w, SEED), "x".repeat(300))).toBe(false)
		expect(pasteInto(nativeInput(w, PAIR[0]), "y".repeat(130))).toBe(true)
		expect(w.emitted("update:password")?.at(-1)).toEqual(["y".repeat(128)])
	})
})
