import { durations, fontSizes, fontWeights, lineHeights, tokenGroups } from "../token-contract"

/**
 * Pure renderer: turns the token contract into the exact source of `src/tokens.ts`.
 * Lives in `src/` so it is typechecked and unit-tested (by `tokens.drift.test.ts`); the Bun CLI
 * that writes the file is `scripts/gen-tokens.ts`. Output must be Biome-clean so the byte-pin drift
 * test and `bun run lint` agree.
 */

const HEADER = `/**
 * GENERATED by scripts/gen-tokens.ts from src/token-contract.ts — DO NOT EDIT.
 * Run \`bun run gen:tokens\` after changing the contract; tokens.drift.test.ts fails CI on
 * divergence. Members are CSS-variable NAMES; use cssVar() to wrap for inline styles.
 */`

function renderKey(k: string): string {
	if (/^[a-z][a-zA-Z0-9]*$/.test(k)) return k
	if (/^[0-9]+$/.test(k)) return k
	return JSON.stringify(k)
}

function renderConst(name: string, members: Record<string, string | number>, quoteValues: boolean): string {
	const body = Object.entries(members)
		.map(([k, v]) => `\t${renderKey(k)}: ${quoteValues ? JSON.stringify(v) : String(v)},`)
		.join("\n")
	return `export const ${name} = {\n${body}\n} as const`
}

export function renderTokensModule(): string {
	const blocks: string[] = [HEADER]

	for (const [group, members] of Object.entries(tokenGroups)) {
		blocks.push(renderConst(group, members as Record<string, string>, true))
	}

	blocks.push(`export const fontSizes = [${(fontSizes as readonly number[]).join(", ")}] as const`)
	blocks.push(`export const fontWeights = [${(fontWeights as readonly number[]).join(", ")}] as const`)
	blocks.push(renderConst("lineHeights", lineHeights as Record<string, number>, false))
	blocks.push(renderConst("durations", durations as Record<string, string>, true))

	blocks.push(
		// biome-ignore lint/suspicious/noTemplateCurlyInString: emits the literal cssVar source, which must contain ${...} placeholders
		"export const cssVar = (name: string, fallback?: string): string => (fallback === undefined ? `var(${name})` : `var(${name}, ${fallback})`)",
	)

	blocks.push(
		[
			"export type SurfaceToken = (typeof surfaces)[keyof typeof surfaces]",
			"export type BrandToken = (typeof brand)[keyof typeof brand]",
			"export type TextToken = (typeof text)[keyof typeof text]",
			"export type ColorToken = (typeof colors)[keyof typeof colors]",
			"export type FontToken = (typeof fonts)[keyof typeof fonts]",
			"export type FontSize = (typeof fontSizes)[number]",
			"export type FontWeight = (typeof fontWeights)[number]",
			"export type LineHeight = keyof typeof lineHeights",
		].join("\n"),
	)

	return `${blocks.join("\n\n")}\n`
}
