import {
	flexAlignments,
	flexDirections,
	flexGaps,
	flexWraps,
	fontSizes,
	fontWeights,
	lineHeights,
	textAligns,
	textColors,
} from "../token-contract"

/**
 * Pure renderer for `src/utilities.css` — the text and flex utility layer,
 * generated from the contract scales so the ~120 classes can't drift by a per-class typo. The static
 * globals (fonts, resets, keyframes, token blocks) live hand-authored in `base.css`. Output must be
 * Biome-clean so the byte-pin (`utilities.drift.test.ts`) and `bun run lint` agree.
 */

const HEADER = `/* GENERATED by scripts/gen-tokens.ts from src/token-contract.ts — DO NOT EDIT.
   Run \`bun run gen:tokens\`; utilities.drift.test.ts fails CI on divergence.
   Modified from Azguard Wallet (https://github.com/AzguardWallet/azguard-wallet), Copyright 2026 BB Strategy Pte. Ltd., Apache-2.0. */`

function rule(selector: string, declaration: string): string {
	return `${selector} {\n\t${declaration}\n}`
}

export function renderUtilitiesCss(): string {
	const blocks: string[] = [HEADER]

	for (const size of fontSizes) blocks.push(rule(`.fz--${size}`, `font-size: ${size}px;`))
	for (const weight of fontWeights) blocks.push(rule(`.fw--${weight}`, `font-weight: ${weight};`))
	for (const [key, value] of Object.entries(lineHeights)) blocks.push(rule(`.lh--${key}`, `line-height: ${value};`))
	for (const [key, value] of Object.entries(textAligns)) blocks.push(rule(`.ta--${key}`, `text-align: ${value};`))
	for (const [key, value] of Object.entries(textColors)) blocks.push(rule(`.color--${key}`, `color: var(${value});`))
	for (const [key, value] of Object.entries(textColors)) blocks.push(rule(`.fill--${key}`, `fill: var(${value});`))

	blocks.push(rule(".flex", "display: flex;"))
	blocks.push(rule(".flex-wide", "width: 100%;"))
	for (const gap of flexGaps) blocks.push(rule(`.gap--${gap}`, `gap: ${gap}px;`))
	for (const [key, value] of Object.entries(flexAlignments)) {
		blocks.push(rule(`.justify-${key}`, `justify-content: ${value};`))
		blocks.push(rule(`.items-${key}`, `align-items: ${value};`))
		blocks.push(rule(`.justify-items-${key}`, `justify-items: ${value};`))
		blocks.push(rule(`.content-${key}`, `align-content: ${value};`))
	}
	for (const [key, value] of Object.entries(flexWraps)) blocks.push(rule(`.wrap-${key}`, `flex-wrap: ${value};`))
	for (const [key, value] of Object.entries(flexDirections)) blocks.push(rule(`.flex-direction-${key}`, `flex-direction: ${value};`))

	return `${blocks.join("\n\n")}\n`
}
