/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACTIVITY_FEED_KINDS: typeof import('../utils/journal-state').ACTIVITY_FEED_KINDS
  const ADDED_COALESCE: typeof import('../utils/coalesce').ADDED_COALESCE
  const ARRIVALS_KEY: typeof import('../composables/useArrivals').ARRIVALS_KEY
  const ARRIVAL_WINDOW_MS: typeof import('../composables/useArrivals').ARRIVAL_WINDOW_MS
  const AccessLevel: typeof import('../utils/confirmation-policies').AccessLevel
  const AssemblyAbortedError: typeof import('../utils/full-backup-helpers').AssemblyAbortedError
  const BootstrapFailedError: typeof import('../composables/unlockWait').BootstrapFailedError
  const CHAIN_IDS: typeof import('../utils/chain-ids').CHAIN_IDS
  const CLEANUP_PENDING_MESSAGE: typeof import('../composables/full-backup-restore').CLEANUP_PENDING_MESSAGE
  const CONTACT_EXISTS: typeof import('../utils/contact-rules').CONTACT_EXISTS
  const CONTACT_NAME_MAX: typeof import('../utils/contact-name').CONTACT_NAME_MAX
  const EffectScope: typeof import('vue').EffectScope
  const EnsureSuperseded: typeof import('../stores/balances.store').EnsureSuperseded
  const EstimateRequeue: typeof import('../utils/estimate-when-clear').EstimateRequeue
  const FEE_JUICE_DECIMALS: typeof import('../utils/fee-estimation').FEE_JUICE_DECIMALS
  const FEE_METHODS: typeof import('../utils/tx-enrichment').FEE_METHODS
  const FIRST_PROFILE_NAME: typeof import('../utils/profile-name').FIRST_PROFILE_NAME
  const FULL_BACKUP_V2_TAG: typeof import('../utils/full-backup-helpers').FULL_BACKUP_V2_TAG
  const FULL_SIZE: typeof import('../utils/hero-fit').FULL_SIZE
  const FilePickCanceledError: typeof import('../utils/files').FilePickCanceledError
  const FileTooLargeError: typeof import('../utils/files').FileTooLargeError
  const GLOSSARY: typeof import('../utils/glossary').GLOSSARY
  const GLOSSARY_SECTIONS: typeof import('../utils/glossary').GLOSSARY_SECTIONS
  const HERO_MIN_SCALE: typeof import('../utils/hero-fit').HERO_MIN_SCALE
  const HOME_TOKEN_ROWS: typeof import('../utils/token-order').HOME_TOKEN_ROWS
  const HOSTNAME_WARNING: typeof import('../composables/useDappHostname').HOSTNAME_WARNING
  const IMPORT_ACTIVATION_TIMEOUT_MS: typeof import('../composables/completeImportWithRecovery').IMPORT_ACTIVATION_TIMEOUT_MS
  const IMPORT_CHAIN_SYNC_TOTAL_BUDGET_MS: typeof import('../composables/importChainSync').IMPORT_CHAIN_SYNC_TOTAL_BUDGET_MS
  const IMPORT_PREFLIGHT_BUDGET_MS: typeof import('../composables/importChainSync').IMPORT_PREFLIGHT_BUDGET_MS
  const IMPORT_REGISTRATION_BUDGET_MS: typeof import('../composables/importChainSync').IMPORT_REGISTRATION_BUDGET_MS
  const INIT_FETCH_TIMEOUT_MS: typeof import('../stores/balances.store').INIT_FETCH_TIMEOUT_MS
  const INIT_RETRY_BACKOFF_MS: typeof import('../stores/balances.store').INIT_RETRY_BACKOFF_MS
  const LEGAL_DECLINED_PATH: typeof import('../utils/legal-sheet').LEGAL_DECLINED_PATH
  const LEGAL_DISMISSED_KEY: typeof import('../utils/legal-sheet').LEGAL_DISMISSED_KEY
  const LOCAL_L1_CHAIN_ID: typeof import('../utils/chain-ids').LOCAL_L1_CHAIN_ID
  const MAINNET_L1_CHAIN_ID: typeof import('../utils/chain-ids').MAINNET_L1_CHAIN_ID
  const MAX_BACKUP_FILE_BYTES: typeof import('../utils/full-backup-helpers').MAX_BACKUP_FILE_BYTES
  const MAX_CONTACT_IMPORT_BYTES: typeof import('../utils/contacts-export-format').MAX_CONTACT_IMPORT_BYTES
  const MAX_CONTACT_IMPORT_ROWS: typeof import('../utils/contacts-export-format').MAX_CONTACT_IMPORT_ROWS
  const MAX_DECIMALS: typeof import('../utils/token-amount').MAX_DECIMALS
  const MINT_SIGNATURES: typeof import('../utils/token-transfer-vocabulary').MINT_SIGNATURES
  const OWN_WINDOW_ROUTES: typeof import('../utils/own-window').OWN_WINDOW_ROUTES
  const PASSKEY_COPY: typeof import('../utils/passkey-copy').PASSKEY_COPY
  const PINNED_TOKENS_MAX: typeof import('../composables/usePinnedTokens').PINNED_TOKENS_MAX
  const PINNED_TOKENS_MAX_CHAINS: typeof import('../composables/usePinnedTokens').PINNED_TOKENS_MAX_CHAINS
  const PROFILE_UI_KEY_PREFIXES: typeof import('../utils/profile-ui-keys').PROFILE_UI_KEY_PREFIXES
  const REVIEW_ARM_MS: typeof import('../composables/useSendReview').REVIEW_ARM_MS
  const SEED_STATUS_RETRY_MS: typeof import('../composables/useSeedStatus').SEED_STATUS_RETRY_MS
  const SNACK_GAP: typeof import('../composables/snackInset').SNACK_GAP
  const STALLED_MIN_DISPLAY_MS: typeof import('../composables/useIncomingSyncHealth').STALLED_MIN_DISPLAY_MS
  const SUCCESS_TOAST_MS: typeof import('../composables/toast.js').SUCCESS_TOAST_MS
  const TESTNET_L1_CHAIN_ID: typeof import('../utils/chain-ids').TESTNET_L1_CHAIN_ID
  const TESTNET_ROLLUP_VERSION: typeof import('../utils/chain-ids').TESTNET_ROLLUP_VERSION
  const THEME_HINT_KEY: typeof import('../utils/general').THEME_HINT_KEY
  const THIRD_PARTY_NOTICES_FILE: typeof import('../utils/legal-links').THIRD_PARTY_NOTICES_FILE
  const TRANSFER_LABELS: typeof import('../utils/token-transfer-vocabulary').TRANSFER_LABELS
  const TRANSFER_SIGNATURES: typeof import('../utils/token-transfer-vocabulary').TRANSFER_SIGNATURES
  const UnlockTimeoutError: typeof import('../composables/unlockWait').UnlockTimeoutError
  const VOCABULARY_SELECTORS: typeof import('../utils/token-transfer-vocabulary').VOCABULARY_SELECTORS
  const abiNameFitsRole: typeof import('../utils/token-transfer-vocabulary').abiNameFitsRole
  const abortableSleep: typeof import('../utils/abortable-sleep').abortableSleep
  const activateNetworkGuarded: typeof import('../utils/guarded-network-activation').activateNetworkGuarded
  const activityRowRoute: typeof import('../utils/activity-rows').activityRowRoute
  const addressChangeText: typeof import('../utils/contact-import-rows').addressChangeText
  const aggregateFiat: typeof import('../utils/token-aggregate').aggregateFiat
  const applyOutcome: typeof import('../composables/full-backup-restore').applyOutcome
  const approvedSendsInFlight: typeof import('../utils/in-flight-send').approvedSendsInFlight
  const arrivalAmount: typeof import('../composables/useArrivals').arrivalAmount
  const arrivalChipLabel: typeof import('../composables/useArrivals').arrivalChipLabel
  const assembleFullBackup: typeof import('../utils/full-backup-helpers').assembleFullBackup
  const awaitLivenessAdvance: typeof import('../utils/background-liveness').awaitLivenessAdvance
  const awaitProfileActivation: typeof import('../composables/unlockWait').awaitProfileActivation
  const backCtaBlocked: typeof import('../utils/full-backup-ctas').backCtaBlocked
  const balanceFormatted: typeof import('../utils/amount').balanceFormatted
  const browser: typeof import('webextension-polyfill')
  const buildActivityRows: typeof import('../utils/activity-rows').buildActivityRows
  const buildIncomingCardProps: typeof import('../utils/received-display').buildIncomingCardProps
  const buildJournalTerminalCardProps: typeof import('../utils/journal-state').buildJournalTerminalCardProps
  const buildRestoreSecret: typeof import('../composables/full-backup-restore').buildRestoreSecret
  const canonicalContactAddress: typeof import('../utils/contact-rules').canonicalContactAddress
  const capRecords: typeof import('../utils/full-backup-helpers').capRecords
  const capTokenRows: typeof import('../utils/token-order').capTokenRows
  const capitalize: typeof import('../utils/string').capitalize
  const captureOwnWindow: typeof import('../utils/own-window').captureOwnWindow
  const categoricalLabel: typeof import('../utils/journal-state').categoricalLabel
  const clampDecimals: typeof import('../utils/amount').clampDecimals
  const classifyImportRow: typeof import('../utils/contact-import-rows').classifyImportRow
  const classifyPasskeyFailure: typeof import('../utils/passkey-copy').classifyPasskeyFailure
  const classifyRow: typeof import('../utils/token-order').classifyRow
  const closeCurrentWindow: typeof import('../utils/close-current-window').closeCurrentWindow
  const closeOwnWindow: typeof import('../utils/own-window').closeOwnWindow
  const coalesce: typeof import('../utils/coalesce').coalesce
  const collectRestoreErrors: typeof import('../utils/full-backup-helpers').collectRestoreErrors
  const compareTokenRows: typeof import('../utils/token-order').compareTokenRows
  const completeImportWithRecovery: typeof import('../composables/completeImportWithRecovery').completeImportWithRecovery
  const compressData: typeof import('../utils/files').compressData
  const computeMaxFee: typeof import('../utils/fee-estimation').computeMaxFee
  const computed: typeof import('vue').computed
  const confirmationPolicies: typeof import('../utils/confirmation-policies').confirmationPolicies
  const contactNameKey: typeof import('../utils/contact-name').contactNameKey
  const copyFor: typeof import('../utils/presto-ui-state').copyFor
  const copyToClipboard: typeof import('../utils/clipboard').copyToClipboard
  const copyWithToast: typeof import('../utils/clipboard').copyWithToast
  const createApp: typeof import('vue').createApp
  const createRunFence: typeof import('../composables/runFence').createRunFence
  const customRef: typeof import('vue').customRef
  const debounce: typeof import('../utils/general').debounce
  const decompressData: typeof import('../utils/files').decompressData
  const defaultProfileName: typeof import('../utils/profile-name').defaultProfileName
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const detailRowsFor: typeof import('../utils/presto-ui-state').detailRowsFor
  const detectBackupType: typeof import('../utils/full-backup-helpers').detectBackupType
  const displaySymbol: typeof import('../utils/tx-amount').displaySymbol
  const downloadFile: typeof import('../utils/files').downloadFile
  const effectScope: typeof import('vue').effectScope
  const estimateWhenClear: typeof import('../utils/estimate-when-clear').estimateWhenClear
  const feeJuicePricingFromUsd: typeof import('../utils/fee-estimation').feeJuicePricingFromUsd
  const feeToUsd: typeof import('../utils/fee-estimation').feeToUsd
  const fiatHeroCandidates: typeof import('../utils/hero-fit').fiatHeroCandidates
  const findMintSignature: typeof import('../utils/token-transfer-vocabulary').findMintSignature
  const findTransferSignature: typeof import('../utils/token-transfer-vocabulary').findTransferSignature
  const fitHero: typeof import('../utils/hero-fit').fitHero
  const foldLabel: typeof import('../utils/token-fold').foldLabel
  const forChain: typeof import('../utils/token-order').forChain
  const formatBaseUnits: typeof import('../utils/amount').formatBaseUnits
  const formatFeeJuice: typeof import('../utils/fee-estimation').formatFeeJuice
  const formatGas: typeof import('../utils/fee-estimation').formatGas
  const formatGasBalance: typeof import('../utils/fee-estimation').formatGasBalance
  const formatSnackAmount: typeof import('../utils/snack-amount').formatSnackAmount
  const formatTransferType: typeof import('../utils/tx-enrichment').formatTransferType
  const getAccount: typeof import('../utils/core').getAccount
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getDecimalSeparator: typeof import('../utils/amount').getDecimalSeparator
  const getInitials: typeof import('../utils/string').getInitials
  const getLastActiveProfileId: typeof import('../utils/lastActiveProfile').getLastActiveProfileId
  const getMethodLabel: typeof import('../utils/tx-enrichment').getMethodLabel
  const getNetwork: typeof import('../utils/core').getNetwork
  const getOriginLabel: typeof import('../utils/tx-enrichment').getOriginLabel
  const getPrimaryCall: typeof import('../utils/tx-enrichment').getPrimaryCall
  const getThousandSeparator: typeof import('../utils/amount').getThousandSeparator
  const getTransaction: typeof import('../utils/core').getTransaction
  const getTxCategory: typeof import('../utils/tx-enrichment').getTxCategory
  const getTxTitle: typeof import('../utils/tx-enrichment').getTxTitle
  const h: typeof import('vue').h
  const handleCancelOrUnconfirmed: typeof import('../utils/passkey-copy').handleCancelOrUnconfirmed
  const hasInFlightSend: typeof import('../utils/in-flight-send').hasInFlightSend
  const hasReachedPresto: typeof import('../utils/presto-ui-state').hasReachedPresto
  const heroRoom: typeof import('../utils/hero-ruler').heroRoom
  const holdHeroFit: typeof import('../utils/hero-fit').holdHeroFit
  const hubValues: typeof import('../utils/settings-labels').hubValues
  const humanizeErrorKind: typeof import('../utils/journal-state').humanizeErrorKind
  const humanizeMethodName: typeof import('../utils/tx-enrichment').humanizeMethodName
  const incomingInScope: typeof import('../utils/activity-rows').incomingInScope
  const incomingRow: typeof import('../utils/activity-rows').incomingRow
  const indexSavedContacts: typeof import('../utils/contact-import-rows').indexSavedContacts
  const initAppServiceContext: typeof import('../utils/core').initAppServiceContext
  const initTransactionService: typeof import('../utils/core').initTransactionService
  const inject: typeof import('vue').inject
  const inputRoom: typeof import('../utils/hero-ruler').inputRoom
  const isActiveScopeRow: typeof import('../utils/token-order').isActiveScopeRow
  const isAmountAboveDustThreshold: typeof import('../utils/incoming-dust').isAmountAboveDustThreshold
  const isApprovedSendInFlight: typeof import('../utils/in-flight-send').isApprovedSendInFlight
  const isBackgroundConnected: typeof import('../utils/core').isBackgroundConnected
  const isEmptyContactName: typeof import('../utils/contact-name').isEmptyContactName
  const isFirefox: typeof import('../utils/browser-surface').isFirefox
  const isForeignProfile: typeof import('../utils/activity-rows').isForeignProfile
  const isHiddenHolding: typeof import('../utils/token-fold').isHiddenHolding
  const isInFlightSend: typeof import('../utils/in-flight-send').isInFlightSend
  const isNewPasswordValid: typeof import('../utils/password').isNewPasswordValid
  const isPasskeyCancel: typeof import('../utils/passkey-copy').isPasskeyCancel
  const isPitchKind: typeof import('../utils/presto-ui-state').isPitchKind
  const isPopupSubmitKey: typeof import('../composables/usePopupEntity').isPopupSubmitKey
  const isPrefersDarkScheme: typeof import('../utils/general').isPrefersDarkScheme
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isRepeatOrComposing: typeof import('../composables/usePopupEntity').isRepeatOrComposing
  const isShallow: typeof import('vue').isShallow
  const isUnknownParsedRow: typeof import('../utils/token-amount').isUnknownParsedRow
  const isUnknownRow: typeof import('../utils/token-amount').isUnknownRow
  const isValidAztecAddress: typeof import('../utils/aztec-address').isValidAztecAddress
  const isValidDecimals: typeof import('../utils/token-amount').isValidDecimals
  const isValidHex: typeof import('../utils/string').isValidHex
  const journalCardIcon: typeof import('../utils/journal-state').journalCardIcon
  const journalCardOriginLabel: typeof import('../utils/journal-state').journalCardOriginLabel
  const journalCardTitle: typeof import('../utils/journal-state').journalCardTitle
  const journalCardTransferTypeLabel: typeof import('../utils/journal-state').journalCardTransferTypeLabel
  const journalTerminalDisplay: typeof import('../utils/journal-state').journalTerminalDisplay
  const knownDecimals: typeof import('../utils/token-amount').knownDecimals
  const legalAboutRow: typeof import('../utils/legal-about').legalAboutRow
  const managers: typeof import('../utils/core').managers
  const markRaw: typeof import('vue').markRaw
  const matchSavedContacts: typeof import('../utils/contact-import-rows').matchSavedContacts
  const matchesQuery: typeof import('../utils/token-search').matchesQuery
  const migrationIdle: typeof import('../utils/storage').migrationIdle
  const moveToOwnWindow: typeof import('../utils/own-window').moveToOwnWindow
  const newPasswordHint: typeof import('../utils/password').newPasswordHint
  const nextAccountName: typeof import('../utils/account-name').nextAccountName
  const nextTick: typeof import('vue').nextTick
  const normalizeAllIds: typeof import('../utils/full-backup-helpers').normalizeAllIds
  const normalizeAmount: typeof import('../utils/amount').normalizeAmount
  const normalizeImportRows: typeof import('../utils/contact-import-rows').normalizeImportRows
  const normalizeProfileName: typeof import('../utils/profile-name').normalizeProfileName
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const openFullBackupText: typeof import('../utils/full-backup-helpers').openFullBackupText
  const openLegalDocument: typeof import('../utils/legal-links').openLegalDocument
  const openThirdPartyNotices: typeof import('../utils/legal-links').openThirdPartyNotices
  const orderTokenRows: typeof import('../utils/token-order').orderTokenRows
  const ownWindowRoute: typeof import('../utils/own-window').ownWindowRoute
  const parseAmountToBaseUnits: typeof import('../utils/amount').parseAmountToBaseUnits
  const parseContactsExport: typeof import('../utils/contacts-export-format').parseContactsExport
  const parseEncryptedBackup: typeof import('../utils/full-backup-helpers').parseEncryptedBackup
  const parseRawBalance: typeof import('../utils/token-amount').parseRawBalance
  const parseTransferIntent: typeof import('../utils/transfer-intent').parseTransferIntent
  const passkeyFailureCopy: typeof import('../utils/passkey-copy').passkeyFailureCopy
  const passkeyNeedsOwnWindow: typeof import('../utils/browser-surface').passkeyNeedsOwnWindow
  const passkeyTag: typeof import('../utils/passkey-copy').passkeyTag
  const persistThemeHint: typeof import('../utils/general').persistThemeHint
  const pickFile: typeof import('../utils/files').pickFile
  const pickPrimaryIndex: typeof import('../utils/primary-method').pickPrimaryIndex
  const pickPrimaryMethod: typeof import('../utils/tx-enrichment').pickPrimaryMethod
  const pinScopeOf: typeof import('../composables/usePinnedTokens').pinScopeOf
  const pinnedTokensKey: typeof import('../utils/profile-ui-keys').pinnedTokensKey
  const planImportWrites: typeof import('../utils/contact-import-rows').planImportWrites
  const postAuthRoute: typeof import('../utils/own-window').postAuthRoute
  const preflightNetworkConnectivity: typeof import('../composables/importPreflight').preflightNetworkConnectivity
  const profileTypeLabel: typeof import('../utils/settings-labels').profileTypeLabel
  const profileUiKeys: typeof import('../utils/profile-ui-keys').profileUiKeys
  const projectArgument: typeof import('../utils/transfer-intent').projectArgument
  const provide: typeof import('vue').provide
  const purgeNumber: typeof import('../utils/amount').purgeNumber
  const reactive: typeof import('vue').reactive
  const readAmountText: typeof import('../utils/amount').readAmountText
  const readBackupFile: typeof import('../utils/full-backup-helpers').readBackupFile
  const readLiveness: typeof import('../utils/background-liveness').readLiveness
  const readonly: typeof import('vue').readonly
  const receivedLabel: typeof import('../utils/received-display').receivedLabel
  const ref: typeof import('vue').ref
  const refreshBalances: typeof import('../utils/core').refreshBalances
  const refuseRepeatEnter: typeof import('../composables/usePopupEntity').refuseRepeatEnter
  const releaseOwnWindow: typeof import('../utils/own-window').releaseOwnWindow
  const relinkRestoredTokenBalances: typeof import('../composables/full-backup-restore').relinkRestoredTokenBalances
  const remapByMap: typeof import('../utils/full-backup-helpers').remapByMap
  const remapNetworkIdByChain: typeof import('../utils/full-backup-helpers').remapNetworkIdByChain
  const requireAccount: typeof import('../utils/core').requireAccount
  const requireNetwork: typeof import('../utils/core').requireNetwork
  const reseedNetworksStage: typeof import('../composables/full-backup-restore').reseedNetworksStage
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveFromDisplay: typeof import('../utils/received-display').resolveFromDisplay
  const resolvePasskeyCredential: typeof import('../composables/full-backup-restore').resolvePasskeyCredential
  const resolveReceivedType: typeof import('../utils/received-display').resolveReceivedType
  const resolveRestoredActiveNetworkIdByChain: typeof import('../utils/full-backup-helpers').resolveRestoredActiveNetworkIdByChain
  const restoreAccountStateStage: typeof import('../composables/full-backup-restore').restoreAccountStateStage
  const restoreAccountsAndFilterOwnedSlices: typeof import('../composables/full-backup-restore').restoreAccountsAndFilterOwnedSlices
  const restoreAccountsStage: typeof import('../composables/full-backup-restore').restoreAccountsStage
  const restoreActiveNetworkPointer: typeof import('../composables/full-backup-restore').restoreActiveNetworkPointer
  const restoreCtaBlocked: typeof import('../utils/full-backup-ctas').restoreCtaBlocked
  const restoreServiceSlices: typeof import('../composables/full-backup-restore').restoreServiceSlices
  const restoreTokensStage: typeof import('../composables/full-backup-restore').restoreTokensStage
  const retryAccountStateStage: typeof import('../composables/full-backup-restore').retryAccountStateStage
  const retryReplacedRows: typeof import('../composables/full-backup-restore').retryReplacedRows
  const rollbackCreatedProfile: typeof import('../composables/full-backup-restore').rollbackCreatedProfile
  const rowDescriptionFor: typeof import('../utils/presto-ui-state').rowDescriptionFor
  const rulerWidth: typeof import('../utils/hero-ruler').rulerWidth
  const runImportChainSync: typeof import('../composables/importChainSync').runImportChainSync
  const runRestoreFailurePath: typeof import('../composables/full-backup-restore').runRestoreFailurePath
  const safeFiatOf: typeof import('../utils/token-amount').safeFiatOf
  const sameContactAddress: typeof import('../utils/contact-rules').sameContactAddress
  const sameContactName: typeof import('../utils/contact-name').sameContactName
  const sanitizeContactName: typeof import('../utils/contact-name').sanitizeContactName
  const sanitizeJournalSubtitle: typeof import('../utils/journal-state').sanitizeJournalSubtitle
  const sanitizePinMap: typeof import('../composables/usePinnedTokens').sanitizePinMap
  const sanitizeString: typeof import('../utils/string').sanitizeString
  const scopedTxRows: typeof import('../utils/activity-rows').scopedTxRows
  const scrubUrls: typeof import('../utils/scrub-urls').scrubUrls
  const sealFullBackupText: typeof import('../utils/full-backup-helpers').sealFullBackupText
  const sendOutcome: typeof import('../utils/journal-state').sendOutcome
  const setLastActiveProfileId: typeof import('../utils/lastActiveProfile').setLastActiveProfileId
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shouldShowLegalSheet: typeof import('../utils/legal-sheet').shouldShowLegalSheet
  const showsDecryptCta: typeof import('../utils/full-backup-ctas').showsDecryptCta
  const showsRestoreCta: typeof import('../utils/full-backup-ctas').showsRestoreCta
  const showsRestoreErrorCtas: typeof import('../utils/full-backup-ctas').showsRestoreErrorCtas
  const smallFieldDecimal: typeof import('../utils/transfer-intent').smallFieldDecimal
  const snackInset: typeof import('../composables/snackInset').snackInset
  const stageSubtitle: typeof import('../utils/card-subtitle').stageSubtitle
  const stepFailedTitle: typeof import('../utils/passkey-copy').stepFailedTitle
  const stillAsShown: typeof import('../utils/contact-import-rows').stillAsShown
  const storageLocalGet: typeof import('../utils/storage').storageLocalGet
  const storageLocalRemove: typeof import('../utils/storage').storageLocalRemove
  const storageLocalSet: typeof import('../utils/storage').storageLocalSet
  const stringCompare: typeof import('../utils/string').stringCompare
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toRestoreError: typeof import('../utils/restore-error').toRestoreError
  const toValue: typeof import('vue').toValue
  const tokenForReceipt: typeof import('../utils/received-display').tokenForReceipt
  const tokenHeroCandidates: typeof import('../utils/hero-fit').tokenHeroCandidates
  const transferLabel: typeof import('../utils/token-transfer-vocabulary').transferLabel
  const triggerRef: typeof import('vue').triggerRef
  const trimAddress: typeof import('../utils/string').trimAddress
  const trustRestoredTokens: typeof import('../composables/full-backup-restore').trustRestoredTokens
  const txAmount: typeof import('../utils/tx-amount').txAmount
  const txBelongsToScope: typeof import('../stores/activity.store').txBelongsToScope
  const txScope: typeof import('../stores/activity.store').txScope
  const typedContactName: typeof import('../utils/contact-name').typedContactName
  const uiStateFromStatus: typeof import('../utils/presto-ui-state').uiStateFromStatus
  const unref: typeof import('vue').unref
  const untilSessionChecked: typeof import('../composables/useDappApprovalWindow').untilSessionChecked
  const unwrapPasskeyFailure: typeof import('../utils/passkey-copy').unwrapPasskeyFailure
  const usdThresholdToMicro: typeof import('../utils/incoming-dust').usdThresholdToMicro
  const useActivityStore: typeof import('../stores/activity.store').useActivityStore
  const useAppStore: typeof import('../stores/app.store').useAppStore
  const useArrivals: typeof import('../composables/useArrivals').useArrivals
  const useAttrs: typeof import('vue').useAttrs
  const useAuthRegistryStatus: typeof import('../composables/useAuthRegistryStatus').useAuthRegistryStatus
  const useBalancesStore: typeof import('../stores/balances.store').useBalancesStore
  const useCacheStore: typeof import('../stores/cache.store').useCacheStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDappApprovalWindow: typeof import('../composables/useDappApprovalWindow').useDappApprovalWindow
  const useDappHostname: typeof import('../composables/useDappHostname').useDappHostname
  const useDappInteractionPayload: typeof import('../composables/useDappInteractionPayload').useDappInteractionPayload
  const useEntityCrud: typeof import('../composables/useEntityCrud').useEntityCrud
  const useEvent: typeof import('../composables/outside.js').useEvent
  const useFeeEstimation: typeof import('../composables/useFeeEstimation').useFeeEstimation
  const useFeeEstimationMap: typeof import('../composables/useFeeEstimationMap').useFeeEstimationMap
  const useFormState: typeof import('../composables/useFormState').useFormState
  const useFullBackupImport: typeof import('../composables/useFullBackupImport').useFullBackupImport
  const useFullscreenPopupSetting: typeof import('../composables/fullscreenPopupSetting').useFullscreenPopupSetting
  const useId: typeof import('vue').useId
  const useIncomingSyncHealth: typeof import('../composables/useIncomingSyncHealth').useIncomingSyncHealth
  const useIncomingTransfers: typeof import('../composables/useIncomingTransfers').useIncomingTransfers
  const useIncomingTrustPrompts: typeof import('../composables/useIncomingTrustPrompts').useIncomingTrustPrompts
  const useLegalAcceptance: typeof import('../composables/useLegalAcceptance').useLegalAcceptance
  const useLink: typeof import('vue-router').useLink
  const useLockWallet: typeof import('../composables/useLockWallet').useLockWallet
  const useModel: typeof import('vue').useModel
  const useNetworkActivation: typeof import('../composables/useNetworkActivation').useNetworkActivation
  const useNotificationStore: typeof import('../stores/notification.store').useNotificationStore
  const useOutside: typeof import('../composables/outside.js').useOutside
  const usePasskeyCeremony: typeof import('../composables/usePasskeyCeremony').usePasskeyCeremony
  const usePinnedTokens: typeof import('../composables/usePinnedTokens').usePinnedTokens
  const usePopupEntity: typeof import('../composables/usePopupEntity').usePopupEntity
  const usePopupStack: typeof import('../composables/usePopupStack').usePopupStack
  const usePopupStore: typeof import('../stores/popup.store').usePopupStore
  const usePrestoCheck: typeof import('../composables/usePrestoCheck').usePrestoCheck
  const usePrestoStatus: typeof import('../composables/usePrestoStatus').usePrestoStatus
  const usePrices: typeof import('../composables/usePrices').usePrices
  const useProfileBootstrap: typeof import('../composables/useProfileBootstrap').useProfileBootstrap
  const useProfileCreateFlow: typeof import('../composables/useProfileCreateFlow').useProfileCreateFlow
  const useProfileImportFlow: typeof import('../composables/useProfileImportFlow').useProfileImportFlow
  const useProfileNameDefault: typeof import('../composables/useProfileNameDefault').useProfileNameDefault
  const useProfileNameField: typeof import('../composables/useProfileNameField').useProfileNameField
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useScopedTokens: typeof import('../composables/useScopedTokens').useScopedTokens
  const useSecretClipboardCopy: typeof import('../composables/useSecretClipboardCopy').useSecretClipboardCopy
  const useSecretCountdown: typeof import('../composables/useSecretCountdown').useSecretCountdown
  const useSeedStatus: typeof import('../composables/useSeedStatus').useSeedStatus
  const useSendReview: typeof import('../composables/useSendReview').useSendReview
  const useSlots: typeof import('vue').useSlots
  const useSnackInset: typeof import('../composables/snackInset').useSnackInset
  const useSyncedRef: typeof import('../composables/syncedRef.js').useSyncedRef
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTicker: typeof import('../composables/ticker').useTicker
  const useToast: typeof import('../composables/toast.js').useToast
  const useTokenBalanceSnapshot: typeof import('../composables/useTokenBalanceSnapshot').useTokenBalanceSnapshot
  const vSnackFooter: typeof import('../composables/snackInset').vSnackFooter
  const vSnackSheet: typeof import('../composables/snackInset').vSnackSheet
  const validateAndMigrateBackup: typeof import('../composables/useFullBackupImport').validateAndMigrateBackup
  const vocabularySelector: typeof import('../utils/token-transfer-vocabulary').vocabularySelector
  const waitForProfileActive: typeof import('../composables/waitForProfileActive').waitForProfileActive
  const walletChainId: typeof import('../utils/chain-ids').walletChainId
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const withTimeout: typeof import('../stores/balances.store').withTimeout
  const withoutId: typeof import('../utils/entity-list').withoutId
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ImportCompletionDeps, ImportCompletionOutcome } from '../composables/completeImportWithRecovery'
  import('../composables/completeImportWithRecovery')
  // @ts-ignore
  export type { RestoreIo, StageFail, StageOutcome, RestoreScratch, ProfileRestoreClient, NetworkRestoreClient, AccountRestoreClient, RestoredNetwork, RestoreData, SliceRestoreClient, AccountStateRetryContext } from '../composables/full-backup-restore'
  import('../composables/full-backup-restore')
  // @ts-ignore
  export type { ImportChainSyncDeps } from '../composables/importChainSync'
  import('../composables/importChainSync')
  // @ts-ignore
  export type { PreflightVerdict, PreflightOptions } from '../composables/importPreflight'
  import('../composables/importPreflight')
  // @ts-ignore
  export type { RunFence } from '../composables/runFence'
  import('../composables/runFence')
  // @ts-ignore
  export type { FooterBox } from '../composables/snackInset'
  import('../composables/snackInset')
  // @ts-ignore
  export type { UnlockTimeoutError, BootstrapFailedError, ProfileActivationWithFailureSubject } from '../composables/unlockWait'
  import('../composables/unlockWait')
  // @ts-ignore
  export type { ArrivalToken, ArrivalChip, ArrivalsServiceLike, UseArrivalsOptions, Arrivals } from '../composables/useArrivals'
  import('../composables/useArrivals')
  // @ts-ignore
  export type { DappWindowError, UseDappApprovalWindowOptions, UseDappApprovalWindowResult } from '../composables/useDappApprovalWindow'
  import('../composables/useDappApprovalWindow')
  // @ts-ignore
  export type { UIDappMetadata, DappInteractionLike, UseDappInteractionPayloadOptions, UseDappInteractionPayloadResult } from '../composables/useDappInteractionPayload'
  import('../composables/useDappInteractionPayload')
  // @ts-ignore
  export type { EntityCrudMode, UseEntityCrudOptions, UseEntityCrudResult } from '../composables/useEntityCrud'
  import('../composables/useEntityCrud')
  // @ts-ignore
  export type { UseFeeEstimationOptions, UseFeeEstimationResult } from '../composables/useFeeEstimation'
  import('../composables/useFeeEstimation')
  // @ts-ignore
  export type { UseFeeEstimationMapOptions, UseFeeEstimationMapResult } from '../composables/useFeeEstimationMap'
  import('../composables/useFeeEstimationMap')
  // @ts-ignore
  export type { FieldDef, FieldHandle, FormState } from '../composables/useFormState'
  import('../composables/useFormState')
  // @ts-ignore
  export type { FullBackupEnvelope, UseFullBackupImportOptions, UseFullBackupImportResult, RestoreStage, RestoreStatus } from '../composables/useFullBackupImport'
  import('../composables/useFullBackupImport')
  // @ts-ignore
  export type { IncomingSyncScope, UseIncomingSyncHealthDeps, UseIncomingSyncHealth } from '../composables/useIncomingSyncHealth'
  import('../composables/useIncomingSyncHealth')
  // @ts-ignore
  export type { IncomingScope, IncomingTransferServiceLike, ConfigServiceLike, PriceServiceLike, UseIncomingTransfersOptions, UseIncomingTransfersResult } from '../composables/useIncomingTransfers'
  import('../composables/useIncomingTransfers')
  // @ts-ignore
  export type { LegalViewStatus } from '../composables/useLegalAcceptance'
  import('../composables/useLegalAcceptance')
  // @ts-ignore
  export type { LockProfileClient } from '../composables/useLockWallet'
  import('../composables/useLockWallet')
  // @ts-ignore
  export type { UseNetworkActivationOptions } from '../composables/useNetworkActivation'
  import('../composables/useNetworkActivation')
  // @ts-ignore
  export type { PinMap, PinScope, PinResult, UsePinnedTokensDeps } from '../composables/usePinnedTokens'
  import('../composables/usePinnedTokens')
  // @ts-ignore
  export type { UsePopupEntityHandlers, UsePopupEntityOptions } from '../composables/usePopupEntity'
  import('../composables/usePopupEntity')
  // @ts-ignore
  export type { PrestoCheckConfig } from '../composables/usePrestoCheck'
  import('../composables/usePrestoCheck')
  // @ts-ignore
  export type { UseProfileCreateFlowOptions } from '../composables/useProfileCreateFlow'
  import('../composables/useProfileCreateFlow')
  // @ts-ignore
  export type { UseProfileImportFlowOptions } from '../composables/useProfileImportFlow'
  import('../composables/useProfileImportFlow')
  // @ts-ignore
  export type { NameFieldState } from '../composables/useProfileNameDefault'
  import('../composables/useProfileNameDefault')
  // @ts-ignore
  export type { ProfileNameFieldOptions, ValidateOptions, ProfileNameField } from '../composables/useProfileNameField'
  import('../composables/useProfileNameField')
  // @ts-ignore
  export type { TokenScope, UseScopedTokensOptions, UseScopedTokensResult } from '../composables/useScopedTokens'
  import('../composables/useScopedTokens')
  // @ts-ignore
  export type { UseSecretCountdownOptions } from '../composables/useSecretCountdown'
  import('../composables/useSecretCountdown')
  // @ts-ignore
  export type { SnapshotState, UseSeedStatusDeps, UseSeedStatus } from '../composables/useSeedStatus'
  import('../composables/useSeedStatus')
  // @ts-ignore
  export type { SubmitSource, SendReview } from '../composables/useSendReview'
  import('../composables/useSendReview')
  // @ts-ignore
  export type { TokenBalanceSnapshotState } from '../composables/useTokenBalanceSnapshot'
  import('../composables/useTokenBalanceSnapshot')
  // @ts-ignore
  export type { ProfileActivationSubject } from '../composables/waitForProfileActive'
  import('../composables/waitForProfileActive')
  // @ts-ignore
  export type { AwaitingTx, ActivitySlice } from '../stores/activity.store'
  import('../stores/activity.store')
  // @ts-ignore
  export type { EnsureSuperseded, BalanceScope, SliceStatus, GasSlice, FpcSlice, BalanceEntry, BalanceLeg, SubscribeCaps, EnsureSnapshot } from '../stores/balances.store'
  import('../stores/balances.store')
  // @ts-ignore
  export type { NotificationType, NotificationPayload, NotificationItem } from '../stores/notification.store'
  import('../stores/notification.store')
  // @ts-ignore
  export type { ActivityRowTx, ActivityRowJournal, ActivityRowIncoming, ActivityRow, BuildActivityRowsParams } from '../utils/activity-rows'
  import('../utils/activity-rows')
  // @ts-ignore
  export type { AmountRead, FormatBaseUnitsOpts } from '../utils/amount'
  import('../utils/amount')
  // @ts-ignore
  export type { CopyToastSpec } from '../utils/clipboard'
  import('../utils/clipboard')
  // @ts-ignore
  export type { ConfirmationPolicy } from '../utils/confirmation-policies'
  import('../utils/confirmation-policies')
  // @ts-ignore
  export type { ImportRow, SavedContactIndex, ContactMatchKind, ContactMatch, ImportRowKind, ClassifiedImportRow, ReviewedImportRow, ImportWrite } from '../utils/contact-import-rows'
  import('../utils/contact-import-rows')
  // @ts-ignore
  export type { ImportedContactV1, ImportedContactV2, ParsedExport } from '../utils/contacts-export-format'
  import('../utils/contacts-export-format')
  // @ts-ignore
  export type { AppServices } from '../utils/core'
  import('../utils/core')
  // @ts-ignore
  export type { EstimateRequeue } from '../utils/estimate-when-clear'
  import('../utils/estimate-when-clear')
  // @ts-ignore
  export type { AssetPricing } from '../utils/fee-estimation'
  import('../utils/fee-estimation')
  // @ts-ignore
  export type { FileTooLargeError, FilePickCanceledError } from '../utils/files'
  import('../utils/files')
  // @ts-ignore
  export type { FullBackupCtaSource } from '../utils/full-backup-ctas'
  import('../utils/full-backup-ctas')
  // @ts-ignore
  export type { AssemblyAbortedError, BackupFileType, BackupSelection, ProcessBackupResult, BackupSource, AssembledBackup } from '../utils/full-backup-helpers'
  import('../utils/full-backup-helpers')
  // @ts-ignore
  export type { GlossaryEntry, GlossaryKey } from '../utils/glossary'
  import('../utils/glossary')
  // @ts-ignore
  export type { NetworkActivationResult } from '../utils/guarded-network-activation'
  import('../utils/guarded-network-activation')
  // @ts-ignore
  export type { HeroFit, HeroWidthAt } from '../utils/hero-fit'
  import('../utils/hero-fit')
  // @ts-ignore
  export type { InFlightScope } from '../utils/in-flight-send'
  import('../utils/in-flight-send')
  // @ts-ignore
  export type { JournalTerminalVisualState, JournalTerminalDisplay, SendOutcome, CategoricalFailureLabel, TokenForCardProps, JournalTerminalCardCtx, JournalTerminalCardProps } from '../utils/journal-state'
  import('../utils/journal-state')
  // @ts-ignore
  export type { LegalAboutRow } from '../utils/legal-about'
  import('../utils/legal-about')
  // @ts-ignore
  export type { LegalSheetContext } from '../utils/legal-sheet'
  import('../utils/legal-sheet')
  // @ts-ignore
  export type { PasskeyTitle, WindowStep, PasskeyFailure } from '../utils/passkey-copy'
  import('../utils/passkey-copy')
  // @ts-ignore
  export type { PrestoInfo, PrestoUiState, PrestoTone, PrestoCopy, PrestoSurface, PrestoDetailRow } from '../utils/presto-ui-state'
  import('../utils/presto-ui-state')
  // @ts-ignore
  export type { MethodCarrier } from '../utils/primary-method'
  import('../utils/primary-method')
  // @ts-ignore
  export type { ReceivedType, FromDisplay } from '../utils/received-display'
  import('../utils/received-display')
  // @ts-ignore
  export type { HubConfig, HubValues } from '../utils/settings-labels'
  import('../utils/settings-labels')
  // @ts-ignore
  export type { Aggregate } from '../utils/token-aggregate'
  import('../utils/token-aggregate')
  // @ts-ignore
  export type { FiatOf } from '../utils/token-amount'
  import('../utils/token-amount')
  // @ts-ignore
  export type { OrderableRow, OrderCtx, RowClass, LiveTokenScope } from '../utils/token-order'
  import('../utils/token-order')
  // @ts-ignore
  export type { TransferKind, MintKind, TransferSignature, MintSignature } from '../utils/token-transfer-vocabulary'
  import('../utils/token-transfer-vocabulary')
  // @ts-ignore
  export type { TransferIntent, ProjectedArgument } from '../utils/transfer-intent'
  import('../utils/transfer-intent')
  // @ts-ignore
  export type { TxAmount } from '../utils/tx-amount'
  import('../utils/tx-amount')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ACTIVITY_FEED_KINDS: UnwrapRef<typeof import('../utils/journal-state')['ACTIVITY_FEED_KINDS']>
    readonly ADDED_COALESCE: UnwrapRef<typeof import('../utils/coalesce')['ADDED_COALESCE']>
    readonly ARRIVALS_KEY: UnwrapRef<typeof import('../composables/useArrivals')['ARRIVALS_KEY']>
    readonly ARRIVAL_WINDOW_MS: UnwrapRef<typeof import('../composables/useArrivals')['ARRIVAL_WINDOW_MS']>
    readonly AccessLevel: UnwrapRef<typeof import('../utils/confirmation-policies')['AccessLevel']>
    readonly AssemblyAbortedError: UnwrapRef<typeof import('../utils/full-backup-helpers')['AssemblyAbortedError']>
    readonly BootstrapFailedError: UnwrapRef<typeof import('../composables/unlockWait')['BootstrapFailedError']>
    readonly CHAIN_IDS: UnwrapRef<typeof import('../utils/chain-ids')['CHAIN_IDS']>
    readonly CLEANUP_PENDING_MESSAGE: UnwrapRef<typeof import('../composables/full-backup-restore')['CLEANUP_PENDING_MESSAGE']>
    readonly CONTACT_EXISTS: UnwrapRef<typeof import('../utils/contact-rules')['CONTACT_EXISTS']>
    readonly CONTACT_NAME_MAX: UnwrapRef<typeof import('../utils/contact-name')['CONTACT_NAME_MAX']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly EnsureSuperseded: UnwrapRef<typeof import('../stores/balances.store')['EnsureSuperseded']>
    readonly EstimateRequeue: UnwrapRef<typeof import('../utils/estimate-when-clear')['EstimateRequeue']>
    readonly FEE_JUICE_DECIMALS: UnwrapRef<typeof import('../utils/fee-estimation')['FEE_JUICE_DECIMALS']>
    readonly FEE_METHODS: UnwrapRef<typeof import('../utils/tx-enrichment')['FEE_METHODS']>
    readonly FIRST_PROFILE_NAME: UnwrapRef<typeof import('../utils/profile-name')['FIRST_PROFILE_NAME']>
    readonly FULL_BACKUP_V2_TAG: UnwrapRef<typeof import('../utils/full-backup-helpers')['FULL_BACKUP_V2_TAG']>
    readonly FULL_SIZE: UnwrapRef<typeof import('../utils/hero-fit')['FULL_SIZE']>
    readonly FilePickCanceledError: UnwrapRef<typeof import('../utils/files')['FilePickCanceledError']>
    readonly FileTooLargeError: UnwrapRef<typeof import('../utils/files')['FileTooLargeError']>
    readonly GLOSSARY: UnwrapRef<typeof import('../utils/glossary')['GLOSSARY']>
    readonly GLOSSARY_SECTIONS: UnwrapRef<typeof import('../utils/glossary')['GLOSSARY_SECTIONS']>
    readonly HERO_MIN_SCALE: UnwrapRef<typeof import('../utils/hero-fit')['HERO_MIN_SCALE']>
    readonly HOME_TOKEN_ROWS: UnwrapRef<typeof import('../utils/token-order')['HOME_TOKEN_ROWS']>
    readonly HOSTNAME_WARNING: UnwrapRef<typeof import('../composables/useDappHostname')['HOSTNAME_WARNING']>
    readonly IMPORT_ACTIVATION_TIMEOUT_MS: UnwrapRef<typeof import('../composables/completeImportWithRecovery')['IMPORT_ACTIVATION_TIMEOUT_MS']>
    readonly IMPORT_CHAIN_SYNC_TOTAL_BUDGET_MS: UnwrapRef<typeof import('../composables/importChainSync')['IMPORT_CHAIN_SYNC_TOTAL_BUDGET_MS']>
    readonly IMPORT_PREFLIGHT_BUDGET_MS: UnwrapRef<typeof import('../composables/importChainSync')['IMPORT_PREFLIGHT_BUDGET_MS']>
    readonly IMPORT_REGISTRATION_BUDGET_MS: UnwrapRef<typeof import('../composables/importChainSync')['IMPORT_REGISTRATION_BUDGET_MS']>
    readonly INIT_FETCH_TIMEOUT_MS: UnwrapRef<typeof import('../stores/balances.store')['INIT_FETCH_TIMEOUT_MS']>
    readonly INIT_RETRY_BACKOFF_MS: UnwrapRef<typeof import('../stores/balances.store')['INIT_RETRY_BACKOFF_MS']>
    readonly LEGAL_DECLINED_PATH: UnwrapRef<typeof import('../utils/legal-sheet')['LEGAL_DECLINED_PATH']>
    readonly LEGAL_DISMISSED_KEY: UnwrapRef<typeof import('../utils/legal-sheet')['LEGAL_DISMISSED_KEY']>
    readonly LOCAL_L1_CHAIN_ID: UnwrapRef<typeof import('../utils/chain-ids')['LOCAL_L1_CHAIN_ID']>
    readonly MAINNET_L1_CHAIN_ID: UnwrapRef<typeof import('../utils/chain-ids')['MAINNET_L1_CHAIN_ID']>
    readonly MAX_BACKUP_FILE_BYTES: UnwrapRef<typeof import('../utils/full-backup-helpers')['MAX_BACKUP_FILE_BYTES']>
    readonly MAX_CONTACT_IMPORT_BYTES: UnwrapRef<typeof import('../utils/contacts-export-format')['MAX_CONTACT_IMPORT_BYTES']>
    readonly MAX_CONTACT_IMPORT_ROWS: UnwrapRef<typeof import('../utils/contacts-export-format')['MAX_CONTACT_IMPORT_ROWS']>
    readonly MAX_DECIMALS: UnwrapRef<typeof import('../utils/token-amount')['MAX_DECIMALS']>
    readonly MINT_SIGNATURES: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['MINT_SIGNATURES']>
    readonly OWN_WINDOW_ROUTES: UnwrapRef<typeof import('../utils/own-window')['OWN_WINDOW_ROUTES']>
    readonly PASSKEY_COPY: UnwrapRef<typeof import('../utils/passkey-copy')['PASSKEY_COPY']>
    readonly PINNED_TOKENS_MAX: UnwrapRef<typeof import('../composables/usePinnedTokens')['PINNED_TOKENS_MAX']>
    readonly PINNED_TOKENS_MAX_CHAINS: UnwrapRef<typeof import('../composables/usePinnedTokens')['PINNED_TOKENS_MAX_CHAINS']>
    readonly PROFILE_UI_KEY_PREFIXES: UnwrapRef<typeof import('../utils/profile-ui-keys')['PROFILE_UI_KEY_PREFIXES']>
    readonly REVIEW_ARM_MS: UnwrapRef<typeof import('../composables/useSendReview')['REVIEW_ARM_MS']>
    readonly SEED_STATUS_RETRY_MS: UnwrapRef<typeof import('../composables/useSeedStatus')['SEED_STATUS_RETRY_MS']>
    readonly SNACK_GAP: UnwrapRef<typeof import('../composables/snackInset')['SNACK_GAP']>
    readonly STALLED_MIN_DISPLAY_MS: UnwrapRef<typeof import('../composables/useIncomingSyncHealth')['STALLED_MIN_DISPLAY_MS']>
    readonly SUCCESS_TOAST_MS: UnwrapRef<typeof import('../composables/toast.js')['SUCCESS_TOAST_MS']>
    readonly TESTNET_L1_CHAIN_ID: UnwrapRef<typeof import('../utils/chain-ids')['TESTNET_L1_CHAIN_ID']>
    readonly TESTNET_ROLLUP_VERSION: UnwrapRef<typeof import('../utils/chain-ids')['TESTNET_ROLLUP_VERSION']>
    readonly THEME_HINT_KEY: UnwrapRef<typeof import('../utils/general')['THEME_HINT_KEY']>
    readonly THIRD_PARTY_NOTICES_FILE: UnwrapRef<typeof import('../utils/legal-links')['THIRD_PARTY_NOTICES_FILE']>
    readonly TRANSFER_LABELS: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['TRANSFER_LABELS']>
    readonly TRANSFER_SIGNATURES: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['TRANSFER_SIGNATURES']>
    readonly UnlockTimeoutError: UnwrapRef<typeof import('../composables/unlockWait')['UnlockTimeoutError']>
    readonly VOCABULARY_SELECTORS: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['VOCABULARY_SELECTORS']>
    readonly abiNameFitsRole: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['abiNameFitsRole']>
    readonly abortableSleep: UnwrapRef<typeof import('../utils/abortable-sleep')['abortableSleep']>
    readonly activateNetworkGuarded: UnwrapRef<typeof import('../utils/guarded-network-activation')['activateNetworkGuarded']>
    readonly activityRowRoute: UnwrapRef<typeof import('../utils/activity-rows')['activityRowRoute']>
    readonly addressChangeText: UnwrapRef<typeof import('../utils/contact-import-rows')['addressChangeText']>
    readonly aggregateFiat: UnwrapRef<typeof import('../utils/token-aggregate')['aggregateFiat']>
    readonly applyOutcome: UnwrapRef<typeof import('../composables/full-backup-restore')['applyOutcome']>
    readonly approvedSendsInFlight: UnwrapRef<typeof import('../utils/in-flight-send')['approvedSendsInFlight']>
    readonly arrivalAmount: UnwrapRef<typeof import('../composables/useArrivals')['arrivalAmount']>
    readonly arrivalChipLabel: UnwrapRef<typeof import('../composables/useArrivals')['arrivalChipLabel']>
    readonly assembleFullBackup: UnwrapRef<typeof import('../utils/full-backup-helpers')['assembleFullBackup']>
    readonly awaitLivenessAdvance: UnwrapRef<typeof import('../utils/background-liveness')['awaitLivenessAdvance']>
    readonly awaitProfileActivation: UnwrapRef<typeof import('../composables/unlockWait')['awaitProfileActivation']>
    readonly backCtaBlocked: UnwrapRef<typeof import('../utils/full-backup-ctas')['backCtaBlocked']>
    readonly balanceFormatted: UnwrapRef<typeof import('../utils/amount')['balanceFormatted']>
    readonly browser: UnwrapRef<typeof import('webextension-polyfill')>
    readonly buildActivityRows: UnwrapRef<typeof import('../utils/activity-rows')['buildActivityRows']>
    readonly buildIncomingCardProps: UnwrapRef<typeof import('../utils/received-display')['buildIncomingCardProps']>
    readonly buildJournalTerminalCardProps: UnwrapRef<typeof import('../utils/journal-state')['buildJournalTerminalCardProps']>
    readonly buildRestoreSecret: UnwrapRef<typeof import('../composables/full-backup-restore')['buildRestoreSecret']>
    readonly canonicalContactAddress: UnwrapRef<typeof import('../utils/contact-rules')['canonicalContactAddress']>
    readonly capRecords: UnwrapRef<typeof import('../utils/full-backup-helpers')['capRecords']>
    readonly capTokenRows: UnwrapRef<typeof import('../utils/token-order')['capTokenRows']>
    readonly capitalize: UnwrapRef<typeof import('../utils/string')['capitalize']>
    readonly captureOwnWindow: UnwrapRef<typeof import('../utils/own-window')['captureOwnWindow']>
    readonly categoricalLabel: UnwrapRef<typeof import('../utils/journal-state')['categoricalLabel']>
    readonly clampDecimals: UnwrapRef<typeof import('../utils/amount')['clampDecimals']>
    readonly classifyImportRow: UnwrapRef<typeof import('../utils/contact-import-rows')['classifyImportRow']>
    readonly classifyPasskeyFailure: UnwrapRef<typeof import('../utils/passkey-copy')['classifyPasskeyFailure']>
    readonly classifyRow: UnwrapRef<typeof import('../utils/token-order')['classifyRow']>
    readonly closeCurrentWindow: UnwrapRef<typeof import('../utils/close-current-window')['closeCurrentWindow']>
    readonly closeOwnWindow: UnwrapRef<typeof import('../utils/own-window')['closeOwnWindow']>
    readonly coalesce: UnwrapRef<typeof import('../utils/coalesce')['coalesce']>
    readonly collectRestoreErrors: UnwrapRef<typeof import('../utils/full-backup-helpers')['collectRestoreErrors']>
    readonly compareTokenRows: UnwrapRef<typeof import('../utils/token-order')['compareTokenRows']>
    readonly completeImportWithRecovery: UnwrapRef<typeof import('../composables/completeImportWithRecovery')['completeImportWithRecovery']>
    readonly compressData: UnwrapRef<typeof import('../utils/files')['compressData']>
    readonly computeMaxFee: UnwrapRef<typeof import('../utils/fee-estimation')['computeMaxFee']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly confirmationPolicies: UnwrapRef<typeof import('../utils/confirmation-policies')['confirmationPolicies']>
    readonly contactNameKey: UnwrapRef<typeof import('../utils/contact-name')['contactNameKey']>
    readonly copyFor: UnwrapRef<typeof import('../utils/presto-ui-state')['copyFor']>
    readonly copyToClipboard: UnwrapRef<typeof import('../utils/clipboard')['copyToClipboard']>
    readonly copyWithToast: UnwrapRef<typeof import('../utils/clipboard')['copyWithToast']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createRunFence: UnwrapRef<typeof import('../composables/runFence')['createRunFence']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debounce: UnwrapRef<typeof import('../utils/general')['debounce']>
    readonly decompressData: UnwrapRef<typeof import('../utils/files')['decompressData']>
    readonly defaultProfileName: UnwrapRef<typeof import('../utils/profile-name')['defaultProfileName']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly detailRowsFor: UnwrapRef<typeof import('../utils/presto-ui-state')['detailRowsFor']>
    readonly detectBackupType: UnwrapRef<typeof import('../utils/full-backup-helpers')['detectBackupType']>
    readonly displaySymbol: UnwrapRef<typeof import('../utils/tx-amount')['displaySymbol']>
    readonly downloadFile: UnwrapRef<typeof import('../utils/files')['downloadFile']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly estimateWhenClear: UnwrapRef<typeof import('../utils/estimate-when-clear')['estimateWhenClear']>
    readonly feeJuicePricingFromUsd: UnwrapRef<typeof import('../utils/fee-estimation')['feeJuicePricingFromUsd']>
    readonly feeToUsd: UnwrapRef<typeof import('../utils/fee-estimation')['feeToUsd']>
    readonly fiatHeroCandidates: UnwrapRef<typeof import('../utils/hero-fit')['fiatHeroCandidates']>
    readonly findMintSignature: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['findMintSignature']>
    readonly findTransferSignature: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['findTransferSignature']>
    readonly fitHero: UnwrapRef<typeof import('../utils/hero-fit')['fitHero']>
    readonly foldLabel: UnwrapRef<typeof import('../utils/token-fold')['foldLabel']>
    readonly forChain: UnwrapRef<typeof import('../utils/token-order')['forChain']>
    readonly formatBaseUnits: UnwrapRef<typeof import('../utils/amount')['formatBaseUnits']>
    readonly formatFeeJuice: UnwrapRef<typeof import('../utils/fee-estimation')['formatFeeJuice']>
    readonly formatGas: UnwrapRef<typeof import('../utils/fee-estimation')['formatGas']>
    readonly formatGasBalance: UnwrapRef<typeof import('../utils/fee-estimation')['formatGasBalance']>
    readonly formatSnackAmount: UnwrapRef<typeof import('../utils/snack-amount')['formatSnackAmount']>
    readonly formatTransferType: UnwrapRef<typeof import('../utils/tx-enrichment')['formatTransferType']>
    readonly getAccount: UnwrapRef<typeof import('../utils/core')['getAccount']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getDecimalSeparator: UnwrapRef<typeof import('../utils/amount')['getDecimalSeparator']>
    readonly getInitials: UnwrapRef<typeof import('../utils/string')['getInitials']>
    readonly getLastActiveProfileId: UnwrapRef<typeof import('../utils/lastActiveProfile')['getLastActiveProfileId']>
    readonly getMethodLabel: UnwrapRef<typeof import('../utils/tx-enrichment')['getMethodLabel']>
    readonly getNetwork: UnwrapRef<typeof import('../utils/core')['getNetwork']>
    readonly getOriginLabel: UnwrapRef<typeof import('../utils/tx-enrichment')['getOriginLabel']>
    readonly getPrimaryCall: UnwrapRef<typeof import('../utils/tx-enrichment')['getPrimaryCall']>
    readonly getThousandSeparator: UnwrapRef<typeof import('../utils/amount')['getThousandSeparator']>
    readonly getTransaction: UnwrapRef<typeof import('../utils/core')['getTransaction']>
    readonly getTxCategory: UnwrapRef<typeof import('../utils/tx-enrichment')['getTxCategory']>
    readonly getTxTitle: UnwrapRef<typeof import('../utils/tx-enrichment')['getTxTitle']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly handleCancelOrUnconfirmed: UnwrapRef<typeof import('../utils/passkey-copy')['handleCancelOrUnconfirmed']>
    readonly hasInFlightSend: UnwrapRef<typeof import('../utils/in-flight-send')['hasInFlightSend']>
    readonly hasReachedPresto: UnwrapRef<typeof import('../utils/presto-ui-state')['hasReachedPresto']>
    readonly heroRoom: UnwrapRef<typeof import('../utils/hero-ruler')['heroRoom']>
    readonly holdHeroFit: UnwrapRef<typeof import('../utils/hero-fit')['holdHeroFit']>
    readonly hubValues: UnwrapRef<typeof import('../utils/settings-labels')['hubValues']>
    readonly humanizeErrorKind: UnwrapRef<typeof import('../utils/journal-state')['humanizeErrorKind']>
    readonly humanizeMethodName: UnwrapRef<typeof import('../utils/tx-enrichment')['humanizeMethodName']>
    readonly incomingInScope: UnwrapRef<typeof import('../utils/activity-rows')['incomingInScope']>
    readonly incomingRow: UnwrapRef<typeof import('../utils/activity-rows')['incomingRow']>
    readonly indexSavedContacts: UnwrapRef<typeof import('../utils/contact-import-rows')['indexSavedContacts']>
    readonly initAppServiceContext: UnwrapRef<typeof import('../utils/core')['initAppServiceContext']>
    readonly initTransactionService: UnwrapRef<typeof import('../utils/core')['initTransactionService']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly inputRoom: UnwrapRef<typeof import('../utils/hero-ruler')['inputRoom']>
    readonly isActiveScopeRow: UnwrapRef<typeof import('../utils/token-order')['isActiveScopeRow']>
    readonly isAmountAboveDustThreshold: UnwrapRef<typeof import('../utils/incoming-dust')['isAmountAboveDustThreshold']>
    readonly isApprovedSendInFlight: UnwrapRef<typeof import('../utils/in-flight-send')['isApprovedSendInFlight']>
    readonly isBackgroundConnected: UnwrapRef<typeof import('../utils/core')['isBackgroundConnected']>
    readonly isEmptyContactName: UnwrapRef<typeof import('../utils/contact-name')['isEmptyContactName']>
    readonly isFirefox: UnwrapRef<typeof import('../utils/browser-surface')['isFirefox']>
    readonly isForeignProfile: UnwrapRef<typeof import('../utils/activity-rows')['isForeignProfile']>
    readonly isHiddenHolding: UnwrapRef<typeof import('../utils/token-fold')['isHiddenHolding']>
    readonly isInFlightSend: UnwrapRef<typeof import('../utils/in-flight-send')['isInFlightSend']>
    readonly isNewPasswordValid: UnwrapRef<typeof import('../utils/password')['isNewPasswordValid']>
    readonly isPasskeyCancel: UnwrapRef<typeof import('../utils/passkey-copy')['isPasskeyCancel']>
    readonly isPitchKind: UnwrapRef<typeof import('../utils/presto-ui-state')['isPitchKind']>
    readonly isPopupSubmitKey: UnwrapRef<typeof import('../composables/usePopupEntity')['isPopupSubmitKey']>
    readonly isPrefersDarkScheme: UnwrapRef<typeof import('../utils/general')['isPrefersDarkScheme']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isRepeatOrComposing: UnwrapRef<typeof import('../composables/usePopupEntity')['isRepeatOrComposing']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isUnknownParsedRow: UnwrapRef<typeof import('../utils/token-amount')['isUnknownParsedRow']>
    readonly isUnknownRow: UnwrapRef<typeof import('../utils/token-amount')['isUnknownRow']>
    readonly isValidAztecAddress: UnwrapRef<typeof import('../utils/aztec-address')['isValidAztecAddress']>
    readonly isValidDecimals: UnwrapRef<typeof import('../utils/token-amount')['isValidDecimals']>
    readonly isValidHex: UnwrapRef<typeof import('../utils/string')['isValidHex']>
    readonly journalCardIcon: UnwrapRef<typeof import('../utils/journal-state')['journalCardIcon']>
    readonly journalCardOriginLabel: UnwrapRef<typeof import('../utils/journal-state')['journalCardOriginLabel']>
    readonly journalCardTitle: UnwrapRef<typeof import('../utils/journal-state')['journalCardTitle']>
    readonly journalCardTransferTypeLabel: UnwrapRef<typeof import('../utils/journal-state')['journalCardTransferTypeLabel']>
    readonly journalTerminalDisplay: UnwrapRef<typeof import('../utils/journal-state')['journalTerminalDisplay']>
    readonly knownDecimals: UnwrapRef<typeof import('../utils/token-amount')['knownDecimals']>
    readonly legalAboutRow: UnwrapRef<typeof import('../utils/legal-about')['legalAboutRow']>
    readonly managers: UnwrapRef<typeof import('../utils/core')['managers']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly matchSavedContacts: UnwrapRef<typeof import('../utils/contact-import-rows')['matchSavedContacts']>
    readonly matchesQuery: UnwrapRef<typeof import('../utils/token-search')['matchesQuery']>
    readonly migrationIdle: UnwrapRef<typeof import('../utils/storage')['migrationIdle']>
    readonly moveToOwnWindow: UnwrapRef<typeof import('../utils/own-window')['moveToOwnWindow']>
    readonly newPasswordHint: UnwrapRef<typeof import('../utils/password')['newPasswordHint']>
    readonly nextAccountName: UnwrapRef<typeof import('../utils/account-name')['nextAccountName']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizeAllIds: UnwrapRef<typeof import('../utils/full-backup-helpers')['normalizeAllIds']>
    readonly normalizeAmount: UnwrapRef<typeof import('../utils/amount')['normalizeAmount']>
    readonly normalizeImportRows: UnwrapRef<typeof import('../utils/contact-import-rows')['normalizeImportRows']>
    readonly normalizeProfileName: UnwrapRef<typeof import('../utils/profile-name')['normalizeProfileName']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly openFullBackupText: UnwrapRef<typeof import('../utils/full-backup-helpers')['openFullBackupText']>
    readonly openLegalDocument: UnwrapRef<typeof import('../utils/legal-links')['openLegalDocument']>
    readonly openThirdPartyNotices: UnwrapRef<typeof import('../utils/legal-links')['openThirdPartyNotices']>
    readonly orderTokenRows: UnwrapRef<typeof import('../utils/token-order')['orderTokenRows']>
    readonly ownWindowRoute: UnwrapRef<typeof import('../utils/own-window')['ownWindowRoute']>
    readonly parseAmountToBaseUnits: UnwrapRef<typeof import('../utils/amount')['parseAmountToBaseUnits']>
    readonly parseContactsExport: UnwrapRef<typeof import('../utils/contacts-export-format')['parseContactsExport']>
    readonly parseEncryptedBackup: UnwrapRef<typeof import('../utils/full-backup-helpers')['parseEncryptedBackup']>
    readonly parseRawBalance: UnwrapRef<typeof import('../utils/token-amount')['parseRawBalance']>
    readonly parseTransferIntent: UnwrapRef<typeof import('../utils/transfer-intent')['parseTransferIntent']>
    readonly passkeyFailureCopy: UnwrapRef<typeof import('../utils/passkey-copy')['passkeyFailureCopy']>
    readonly passkeyNeedsOwnWindow: UnwrapRef<typeof import('../utils/browser-surface')['passkeyNeedsOwnWindow']>
    readonly passkeyTag: UnwrapRef<typeof import('../utils/passkey-copy')['passkeyTag']>
    readonly persistThemeHint: UnwrapRef<typeof import('../utils/general')['persistThemeHint']>
    readonly pickFile: UnwrapRef<typeof import('../utils/files')['pickFile']>
    readonly pickPrimaryIndex: UnwrapRef<typeof import('../utils/primary-method')['pickPrimaryIndex']>
    readonly pickPrimaryMethod: UnwrapRef<typeof import('../utils/tx-enrichment')['pickPrimaryMethod']>
    readonly pinScopeOf: UnwrapRef<typeof import('../composables/usePinnedTokens')['pinScopeOf']>
    readonly pinnedTokensKey: UnwrapRef<typeof import('../utils/profile-ui-keys')['pinnedTokensKey']>
    readonly planImportWrites: UnwrapRef<typeof import('../utils/contact-import-rows')['planImportWrites']>
    readonly postAuthRoute: UnwrapRef<typeof import('../utils/own-window')['postAuthRoute']>
    readonly preflightNetworkConnectivity: UnwrapRef<typeof import('../composables/importPreflight')['preflightNetworkConnectivity']>
    readonly profileTypeLabel: UnwrapRef<typeof import('../utils/settings-labels')['profileTypeLabel']>
    readonly profileUiKeys: UnwrapRef<typeof import('../utils/profile-ui-keys')['profileUiKeys']>
    readonly projectArgument: UnwrapRef<typeof import('../utils/transfer-intent')['projectArgument']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly purgeNumber: UnwrapRef<typeof import('../utils/amount')['purgeNumber']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readAmountText: UnwrapRef<typeof import('../utils/amount')['readAmountText']>
    readonly readBackupFile: UnwrapRef<typeof import('../utils/full-backup-helpers')['readBackupFile']>
    readonly readLiveness: UnwrapRef<typeof import('../utils/background-liveness')['readLiveness']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly receivedLabel: UnwrapRef<typeof import('../utils/received-display')['receivedLabel']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refreshBalances: UnwrapRef<typeof import('../utils/core')['refreshBalances']>
    readonly refuseRepeatEnter: UnwrapRef<typeof import('../composables/usePopupEntity')['refuseRepeatEnter']>
    readonly releaseOwnWindow: UnwrapRef<typeof import('../utils/own-window')['releaseOwnWindow']>
    readonly relinkRestoredTokenBalances: UnwrapRef<typeof import('../composables/full-backup-restore')['relinkRestoredTokenBalances']>
    readonly remapByMap: UnwrapRef<typeof import('../utils/full-backup-helpers')['remapByMap']>
    readonly remapNetworkIdByChain: UnwrapRef<typeof import('../utils/full-backup-helpers')['remapNetworkIdByChain']>
    readonly requireAccount: UnwrapRef<typeof import('../utils/core')['requireAccount']>
    readonly requireNetwork: UnwrapRef<typeof import('../utils/core')['requireNetwork']>
    readonly reseedNetworksStage: UnwrapRef<typeof import('../composables/full-backup-restore')['reseedNetworksStage']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveFromDisplay: UnwrapRef<typeof import('../utils/received-display')['resolveFromDisplay']>
    readonly resolvePasskeyCredential: UnwrapRef<typeof import('../composables/full-backup-restore')['resolvePasskeyCredential']>
    readonly resolveReceivedType: UnwrapRef<typeof import('../utils/received-display')['resolveReceivedType']>
    readonly resolveRestoredActiveNetworkIdByChain: UnwrapRef<typeof import('../utils/full-backup-helpers')['resolveRestoredActiveNetworkIdByChain']>
    readonly restoreAccountStateStage: UnwrapRef<typeof import('../composables/full-backup-restore')['restoreAccountStateStage']>
    readonly restoreAccountsAndFilterOwnedSlices: UnwrapRef<typeof import('../composables/full-backup-restore')['restoreAccountsAndFilterOwnedSlices']>
    readonly restoreAccountsStage: UnwrapRef<typeof import('../composables/full-backup-restore')['restoreAccountsStage']>
    readonly restoreActiveNetworkPointer: UnwrapRef<typeof import('../composables/full-backup-restore')['restoreActiveNetworkPointer']>
    readonly restoreCtaBlocked: UnwrapRef<typeof import('../utils/full-backup-ctas')['restoreCtaBlocked']>
    readonly restoreServiceSlices: UnwrapRef<typeof import('../composables/full-backup-restore')['restoreServiceSlices']>
    readonly restoreTokensStage: UnwrapRef<typeof import('../composables/full-backup-restore')['restoreTokensStage']>
    readonly retryAccountStateStage: UnwrapRef<typeof import('../composables/full-backup-restore')['retryAccountStateStage']>
    readonly retryReplacedRows: UnwrapRef<typeof import('../composables/full-backup-restore')['retryReplacedRows']>
    readonly rollbackCreatedProfile: UnwrapRef<typeof import('../composables/full-backup-restore')['rollbackCreatedProfile']>
    readonly rowDescriptionFor: UnwrapRef<typeof import('../utils/presto-ui-state')['rowDescriptionFor']>
    readonly rulerWidth: UnwrapRef<typeof import('../utils/hero-ruler')['rulerWidth']>
    readonly runImportChainSync: UnwrapRef<typeof import('../composables/importChainSync')['runImportChainSync']>
    readonly runRestoreFailurePath: UnwrapRef<typeof import('../composables/full-backup-restore')['runRestoreFailurePath']>
    readonly safeFiatOf: UnwrapRef<typeof import('../utils/token-amount')['safeFiatOf']>
    readonly sameContactAddress: UnwrapRef<typeof import('../utils/contact-rules')['sameContactAddress']>
    readonly sameContactName: UnwrapRef<typeof import('../utils/contact-name')['sameContactName']>
    readonly sanitizeContactName: UnwrapRef<typeof import('../utils/contact-name')['sanitizeContactName']>
    readonly sanitizeJournalSubtitle: UnwrapRef<typeof import('../utils/journal-state')['sanitizeJournalSubtitle']>
    readonly sanitizePinMap: UnwrapRef<typeof import('../composables/usePinnedTokens')['sanitizePinMap']>
    readonly sanitizeString: UnwrapRef<typeof import('../utils/string')['sanitizeString']>
    readonly scopedTxRows: UnwrapRef<typeof import('../utils/activity-rows')['scopedTxRows']>
    readonly scrubUrls: UnwrapRef<typeof import('../utils/scrub-urls')['scrubUrls']>
    readonly sealFullBackupText: UnwrapRef<typeof import('../utils/full-backup-helpers')['sealFullBackupText']>
    readonly sendOutcome: UnwrapRef<typeof import('../utils/journal-state')['sendOutcome']>
    readonly setLastActiveProfileId: UnwrapRef<typeof import('../utils/lastActiveProfile')['setLastActiveProfileId']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly shouldShowLegalSheet: UnwrapRef<typeof import('../utils/legal-sheet')['shouldShowLegalSheet']>
    readonly showsDecryptCta: UnwrapRef<typeof import('../utils/full-backup-ctas')['showsDecryptCta']>
    readonly showsRestoreCta: UnwrapRef<typeof import('../utils/full-backup-ctas')['showsRestoreCta']>
    readonly showsRestoreErrorCtas: UnwrapRef<typeof import('../utils/full-backup-ctas')['showsRestoreErrorCtas']>
    readonly smallFieldDecimal: UnwrapRef<typeof import('../utils/transfer-intent')['smallFieldDecimal']>
    readonly snackInset: UnwrapRef<typeof import('../composables/snackInset')['snackInset']>
    readonly stageSubtitle: UnwrapRef<typeof import('../utils/card-subtitle')['stageSubtitle']>
    readonly stepFailedTitle: UnwrapRef<typeof import('../utils/passkey-copy')['stepFailedTitle']>
    readonly stillAsShown: UnwrapRef<typeof import('../utils/contact-import-rows')['stillAsShown']>
    readonly storageLocalGet: UnwrapRef<typeof import('../utils/storage')['storageLocalGet']>
    readonly storageLocalRemove: UnwrapRef<typeof import('../utils/storage')['storageLocalRemove']>
    readonly storageLocalSet: UnwrapRef<typeof import('../utils/storage')['storageLocalSet']>
    readonly stringCompare: UnwrapRef<typeof import('../utils/string')['stringCompare']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toRestoreError: UnwrapRef<typeof import('../utils/restore-error')['toRestoreError']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly tokenForReceipt: UnwrapRef<typeof import('../utils/received-display')['tokenForReceipt']>
    readonly tokenHeroCandidates: UnwrapRef<typeof import('../utils/hero-fit')['tokenHeroCandidates']>
    readonly transferLabel: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['transferLabel']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly trimAddress: UnwrapRef<typeof import('../utils/string')['trimAddress']>
    readonly trustRestoredTokens: UnwrapRef<typeof import('../composables/full-backup-restore')['trustRestoredTokens']>
    readonly txAmount: UnwrapRef<typeof import('../utils/tx-amount')['txAmount']>
    readonly txBelongsToScope: UnwrapRef<typeof import('../stores/activity.store')['txBelongsToScope']>
    readonly txScope: UnwrapRef<typeof import('../stores/activity.store')['txScope']>
    readonly typedContactName: UnwrapRef<typeof import('../utils/contact-name')['typedContactName']>
    readonly uiStateFromStatus: UnwrapRef<typeof import('../utils/presto-ui-state')['uiStateFromStatus']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly untilSessionChecked: UnwrapRef<typeof import('../composables/useDappApprovalWindow')['untilSessionChecked']>
    readonly unwrapPasskeyFailure: UnwrapRef<typeof import('../utils/passkey-copy')['unwrapPasskeyFailure']>
    readonly usdThresholdToMicro: UnwrapRef<typeof import('../utils/incoming-dust')['usdThresholdToMicro']>
    readonly useActivityStore: UnwrapRef<typeof import('../stores/activity.store')['useActivityStore']>
    readonly useAppStore: UnwrapRef<typeof import('../stores/app.store')['useAppStore']>
    readonly useArrivals: UnwrapRef<typeof import('../composables/useArrivals')['useArrivals']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthRegistryStatus: UnwrapRef<typeof import('../composables/useAuthRegistryStatus')['useAuthRegistryStatus']>
    readonly useBalancesStore: UnwrapRef<typeof import('../stores/balances.store')['useBalancesStore']>
    readonly useCacheStore: UnwrapRef<typeof import('../stores/cache.store')['useCacheStore']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDappApprovalWindow: UnwrapRef<typeof import('../composables/useDappApprovalWindow')['useDappApprovalWindow']>
    readonly useDappHostname: UnwrapRef<typeof import('../composables/useDappHostname')['useDappHostname']>
    readonly useDappInteractionPayload: UnwrapRef<typeof import('../composables/useDappInteractionPayload')['useDappInteractionPayload']>
    readonly useEntityCrud: UnwrapRef<typeof import('../composables/useEntityCrud')['useEntityCrud']>
    readonly useEvent: UnwrapRef<typeof import('../composables/outside.js')['useEvent']>
    readonly useFeeEstimation: UnwrapRef<typeof import('../composables/useFeeEstimation')['useFeeEstimation']>
    readonly useFeeEstimationMap: UnwrapRef<typeof import('../composables/useFeeEstimationMap')['useFeeEstimationMap']>
    readonly useFormState: UnwrapRef<typeof import('../composables/useFormState')['useFormState']>
    readonly useFullBackupImport: UnwrapRef<typeof import('../composables/useFullBackupImport')['useFullBackupImport']>
    readonly useFullscreenPopupSetting: UnwrapRef<typeof import('../composables/fullscreenPopupSetting')['useFullscreenPopupSetting']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useIncomingSyncHealth: UnwrapRef<typeof import('../composables/useIncomingSyncHealth')['useIncomingSyncHealth']>
    readonly useIncomingTransfers: UnwrapRef<typeof import('../composables/useIncomingTransfers')['useIncomingTransfers']>
    readonly useIncomingTrustPrompts: UnwrapRef<typeof import('../composables/useIncomingTrustPrompts')['useIncomingTrustPrompts']>
    readonly useLegalAcceptance: UnwrapRef<typeof import('../composables/useLegalAcceptance')['useLegalAcceptance']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLockWallet: UnwrapRef<typeof import('../composables/useLockWallet')['useLockWallet']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNetworkActivation: UnwrapRef<typeof import('../composables/useNetworkActivation')['useNetworkActivation']>
    readonly useNotificationStore: UnwrapRef<typeof import('../stores/notification.store')['useNotificationStore']>
    readonly useOutside: UnwrapRef<typeof import('../composables/outside.js')['useOutside']>
    readonly usePasskeyCeremony: UnwrapRef<typeof import('../composables/usePasskeyCeremony')['usePasskeyCeremony']>
    readonly usePinnedTokens: UnwrapRef<typeof import('../composables/usePinnedTokens')['usePinnedTokens']>
    readonly usePopupEntity: UnwrapRef<typeof import('../composables/usePopupEntity')['usePopupEntity']>
    readonly usePopupStack: UnwrapRef<typeof import('../composables/usePopupStack')['usePopupStack']>
    readonly usePopupStore: UnwrapRef<typeof import('../stores/popup.store')['usePopupStore']>
    readonly usePrestoCheck: UnwrapRef<typeof import('../composables/usePrestoCheck')['usePrestoCheck']>
    readonly usePrestoStatus: UnwrapRef<typeof import('../composables/usePrestoStatus')['usePrestoStatus']>
    readonly usePrices: UnwrapRef<typeof import('../composables/usePrices')['usePrices']>
    readonly useProfileBootstrap: UnwrapRef<typeof import('../composables/useProfileBootstrap')['useProfileBootstrap']>
    readonly useProfileCreateFlow: UnwrapRef<typeof import('../composables/useProfileCreateFlow')['useProfileCreateFlow']>
    readonly useProfileImportFlow: UnwrapRef<typeof import('../composables/useProfileImportFlow')['useProfileImportFlow']>
    readonly useProfileNameDefault: UnwrapRef<typeof import('../composables/useProfileNameDefault')['useProfileNameDefault']>
    readonly useProfileNameField: UnwrapRef<typeof import('../composables/useProfileNameField')['useProfileNameField']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useScopedTokens: UnwrapRef<typeof import('../composables/useScopedTokens')['useScopedTokens']>
    readonly useSecretClipboardCopy: UnwrapRef<typeof import('../composables/useSecretClipboardCopy')['useSecretClipboardCopy']>
    readonly useSecretCountdown: UnwrapRef<typeof import('../composables/useSecretCountdown')['useSecretCountdown']>
    readonly useSeedStatus: UnwrapRef<typeof import('../composables/useSeedStatus')['useSeedStatus']>
    readonly useSendReview: UnwrapRef<typeof import('../composables/useSendReview')['useSendReview']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSnackInset: UnwrapRef<typeof import('../composables/snackInset')['useSnackInset']>
    readonly useSyncedRef: UnwrapRef<typeof import('../composables/syncedRef.js')['useSyncedRef']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTicker: UnwrapRef<typeof import('../composables/ticker')['useTicker']>
    readonly useToast: UnwrapRef<typeof import('../composables/toast.js')['useToast']>
    readonly useTokenBalanceSnapshot: UnwrapRef<typeof import('../composables/useTokenBalanceSnapshot')['useTokenBalanceSnapshot']>
    readonly vSnackFooter: UnwrapRef<typeof import('../composables/snackInset')['vSnackFooter']>
    readonly vSnackSheet: UnwrapRef<typeof import('../composables/snackInset')['vSnackSheet']>
    readonly validateAndMigrateBackup: UnwrapRef<typeof import('../composables/useFullBackupImport')['validateAndMigrateBackup']>
    readonly vocabularySelector: UnwrapRef<typeof import('../utils/token-transfer-vocabulary')['vocabularySelector']>
    readonly waitForProfileActive: UnwrapRef<typeof import('../composables/waitForProfileActive')['waitForProfileActive']>
    readonly walletChainId: UnwrapRef<typeof import('../utils/chain-ids')['walletChainId']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly withTimeout: UnwrapRef<typeof import('../stores/balances.store')['withTimeout']>
    readonly withoutId: UnwrapRef<typeof import('../utils/entity-list')['withoutId']>
  }
}