import { Fr } from "@aztec-labs/foundation/curves/bn254"
import { deriveKeys } from "@aztec-labs/stdlib/keys"
import { deriveNuloAccountKeys, deriveSigningKeyFromSeed } from "@nulo/wallet-crypto"
import type { ILogger } from "@nulo/wallet-core/logger"
import { describe, expect, test } from "vitest"
import referenceVectors from "../../../../reference/key-model-v2/vectors.json"
import v6Vectors from "../../../../reference/nulo-v6/vectors.json"
import { NuloAccount } from "./nulo-account"

/**
 * Full-chain known-answer test for the signing-key-root inversion (NULO-ACCOUNT-KDF v2).
 *
 * The expected values are REFERENCE-GENERATED by a committed script that never touches this
 * repo's helpers; the address comes from upstream's own `getSchnorrAccountContractAddress` oracle.
 * Key-level values come from the published 5.0.1 packages (`reference/key-model-v2/
 * derive-vectors.ts`; the v1 predecessor vectors stay in `reference/aztec-5.0.0-stable/`), so this
 * stays a cross-version KAT. Address-level values come from the nulo-v6 regime's copy of that
 * script on the published 6.0.0-rc.1 packages (`reference/nulo-v6/`). Equality is the gate — a
 * mismatch means OUR derivation diverged; stop and investigate, never re-pin from the
 * implementation under test.
 */
const nullLogger: ILogger = { log: () => {} }

/** Everything but the address-level values and the generator's own metadata. */
const NOT_KEY_LEVEL = new Set(["address", "partialAddress", "source", "artifact"])
const keyLevel = (vectors: unknown): unknown =>
	JSON.parse(JSON.stringify(vectors), (key, value) => (NOT_KEY_LEVEL.has(key) ? undefined : value))

describe("NULO-ACCOUNT-KDF v2 — full chain vs the reference vectors", () => {
	test("the nulo-v6 reference derives every key-level value the key-model-v2 reference does", () => {
		expect(keyLevel(v6Vectors)).toEqual(keyLevel(referenceVectors))
	})

	for (const vector of referenceVectors.signingChain) {
		const seed = Fr.fromHexString(vector.seed)
		const v6 = v6Vectors.signingChain.find((row) => row.seed === vector.seed)

		test(`seed ${vector.seed.slice(0, 10)}… derives the reference signing/secret keys`, async () => {
			const { signingKey, secretKey } = await deriveNuloAccountKeys(seed)
			expect(signingKey.toString()).toBe(vector.signingKey)
			expect(deriveSigningKeyFromSeed(seed).toString()).toBe(vector.signingKey)
			expect(secretKey.toString()).toBe(vector.secretKey)
		})

		test(`seed ${vector.seed.slice(0, 10)}… derives the reference AccountPrivacyKeys wire value`, async () => {
			const { secretKey, signingKey } = await deriveNuloAccountKeys(seed)
			const keys = await deriveKeys(secretKey)
			// The exact struct the offscreen seam hands to pxe.registerAccount: four privacy
			// SECRETS + two PUBLIC keys. Provably derived material — and provably NOT the seed
			// nor the signing key (the hygiene pin).
			const wire = {
				masterNullifierHidingSecretKey: keys.masterNullifierHidingSecretKey.toString(),
				masterIncomingViewingSecretKey: keys.masterIncomingViewingSecretKey.toString(),
				masterOutgoingViewingSecretKey: keys.masterOutgoingViewingSecretKey.toString(),
				masterTaggingSecretKey: keys.masterTaggingSecretKey.toString(),
				masterMessageSigningPublicKey: keys.masterMessageSigningPublicKey.toString(),
				masterFallbackPublicKey: keys.masterFallbackPublicKey.toString(),
			}
			expect(wire).toEqual(vector.accountPrivacyKeys)
			for (const value of Object.values(wire)) {
				expect(value).not.toBe(seed.toString())
				expect(value).not.toBe(signingKey.toString())
			}
		})

		test(`seed ${vector.seed.slice(0, 10)}… NuloAccount derives the reference address`, async () => {
			if (!v6) throw new Error(`reference/nulo-v6 has no signing-chain row for seed ${vector.seed}`)
			const account = await NuloAccount.new(seed, nullLogger)
			expect(account.address.toString()).toBe(v6.address)
			const complete = await account.getCompleteAddress()
			expect(complete.address.toString()).toBe(v6.completeAddress.address)
			expect(complete.partialAddress.toString()).toBe(v6.completeAddress.partialAddress)
			expect(complete.publicKeys.toString()).toBe(vector.completeAddress.publicKeys)
		})
	}
})
