/**
 * Composition: importing contacts from a picked file to stored rows, in-process. Real: the
 * ImportContactsPopup the person reads and chooses in, the composable (pick, parse, apply, export),
 * the row model, and ContactService (lock, profile fence, events, EntityStorage over FakeBrowserApi).
 * Dumb fakes at the boundaries only: the picked file is a string, the download is captured, the
 * profile is a stub, and the account-state port is a set of registered senders. That set shows what
 * the import asks the PXE to register, not what the PXE stores; `network/senders-advanced` covers
 * the PXE. No PXE, no bb, no simulation (`tests/COMPOSITION-TESTS.md`). Assertions read stored rows
 * and the sender set.
 *
 * The two fixtures are what the released wallet writes: the contacts export, and a full backup
 * holding contacts. Both formats are unchanged since v0.30.2. Each fixture is generated by the code
 * its pin test runs: `NULO_WRITE_CONTACT_FIXTURES=1` writes a missing file and never an existing one.
 * A format change adds a new file and moves the pin to it; the old file keeps its import test.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { flushPromises, mount, type VueWrapper } from "@vue/test-utils"
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest"
import { ref } from "vue"
import { FakeBrowserApi } from "@nulo/wallet-core/testing"
import { assembleFullBackup, normalizeAllIds } from "@/utils/full-backup-helpers"
import { restoreServiceSlices } from "@/composables/full-backup-restore"
import { validateAndMigrateBackup } from "@/composables/useFullBackupImport"
import { useCacheStore } from "@/stores/cache.store"
import { ServiceCollection } from "@/wallet/base"
import { ConfigStore } from "@/wallet/config"
import { LoggerStore } from "@/wallet/logger"
import { BACKUP_SCHEMA_VERSION_FIELD, COMPAT_EPOCH_FIELD, CURRENT_COMPAT_EPOCH } from "@/wallet/services/backup/backup-migration-registry"
import { CURRENT_BACKUP_SCHEMA_VERSION } from "@/wallet/services/backup/backup-migrator"
import { svc } from "@/wallet/services/composition-harness"
import { ContactService } from "@/wallet/services/contact/service"
import { type Contact, CONTACT_SERVICE_NAME, CONTACT_STORAGE_ROOT } from "@/wallet/services/contact/spec"
import { ProfileDeletionState } from "@/wallet/services/profile/profile-deletion-state"
import { PROFILE_SERVICE_NAME, type RunFence } from "@/wallet/services/profile/spec"
import { SessionEndedError } from "@nulo/extension-messaging/errors"

const boundary = vi.hoisted(() => ({
	file: null as { size: number; text: () => Promise<string> } | null,
	downloads: [] as string[],
	toasts: [] as Array<{ kind: string; label: string }>,
	opened: [] as string[],
	service: null as unknown,
	/** The background's profile service, which the popup's own profile client reaches too. */
	profile: null as unknown,
}))

vi.mock("@/utils", async (importOriginal) => ({
	...(await importOriginal<typeof import("@/utils")>()),
	pickFile: async () => boundary.file,
	downloadFile: async ({ data }: { data: string }) => {
		boundary.downloads.push(data)
	},
}))
vi.mock("@/composables/toast", () => ({
	useToast: () => ({ openToast: (toast: { kind: string; label: string }) => boundary.toasts.push(toast) }),
}))
vi.mock("@/stores/app.store", () => ({ useAppStore: () => ({ network: { id: "net-1", name: "Testnet" } }) }))
vi.mock("@/stores/cache.store", async () => {
	const { reactive } = await import("vue")
	const state = reactive({ importContacts: [] as unknown[], importContact: null as unknown, importPromise: null as unknown })
	return { useCacheStore: () => state }
})
vi.mock("@/stores/popup.store", () => ({
	usePopupStore: () => ({ len: 1, popups: { import_contacts: { order: 1 } }, open: (name: string) => boundary.opened.push(name) }),
}))
vi.mock("@/wallet/services/profile/client", () => ({
	ProfileServiceClient: vi.fn(function () {
		const profile = boundary.profile as ProfileStub
		return {
			connect() {},
			disconnect() {},
			getActiveProfile: async () => ({ name: "Main" }),
			captureRunFence: () => profile.captureRunFence(),
			assertRunFence: (fence: RunFence) => profile.assertRunFence(fence),
		}
	}),
}))
// The popup's port to the contact service, wired straight to the real service in this process.
vi.mock("@/wallet/services/contact/client", () => ({
	ContactServiceClient: vi.fn(function () {
		const service = boundary.service as ContactService
		return {
			getContacts: () => service.getContacts(),
			onContactAdded: service.onContactAdded,
			onContactUpdated: service.onContactUpdated,
			onContactDeleted: service.onContactDeleted,
			disconnect() {},
		}
	}),
}))

import ImportContactsPopup from "@/popup/components/popups/ImportContactsPopup.vue"
import { useContactImportExport } from "./useContactImportExport"

const STUBS = {
	Popup: { props: ["show"], template: "<div v-if='show'><slot /></div>" },
	PopupCard: { template: "<div><slot /></div>" },
	Flex: { template: "<div><slot /></div>" },
	Text: { template: "<span><slot /></span>" },
	Icon: { template: "<i />" },
	Button: { template: "<button><slot /></button>" },
	RowAction: { props: ["label"], template: "<button type='button' :aria-label='label' @click.stop><slot /></button>" },
	SectionLabel: { props: ["label", "count", "countTestid"], template: "<div>{{ label }} {{ count }}</div>" },
}

// Wire-shaped: 0x + 64 hex, each the x coordinate of a Grumpkin point.
const ADDR = {
	a: "0x01904dba18e847d163097ce15dcd8597e763fb11fe19ef1273d266d6e959ec4a",
	b: "0x09c1c9d2ce72c53c2451f8e9add86ccb8cb284dd4dc4f0eaf301b40b38a9459b",
	c: "0x048b29517cddb7566a05a2a292624eb2c5350dbe44350763cefe4c9207344c10",
	d: "0x0402f387a230066a23abced99a2348c1ba902c95518bdc2f9447a0ca51e5cbe2",
	e: "0x02056523b85ea4e550facca78516f7270f18bddb0f5474177d406f6bf0e58617",
	f: "0x047bb28204a2545c566dff691c298d2023fe7cad44bb6468e3f7f1e633f8f7d2",
	g: "0x055145d8ad104260f2a5f750fcd8738438d8c33875c52f654202098ae1a8c12c",
	h: "0x0020743f567f996bf9798d57f5304fc8f3652a6888fec4804616dcf847f7e1a7",
	i: "0x077e0014c77c6aa87b49ca24d3c49e945fede32ccae9f1de8d89163827035429",
	j: "0x004c688fd6ed78e95b2a82b7a5ddc6bcd329393f23efb30aa853ab0fc8c5b7dc",
}
// 0x + 64 hex that is not the x coordinate of a Grumpkin point.
const OFF_CURVE = "0x0895f3902a26c15e2f159778cd7848cf9048fce777ee8f41dc90a9fe6b50fc09"
const upper = (address: string) => `0x${address.slice(2).toUpperCase()}`

const CURRENT_EXPORT_FIXTURE = join(__dirname, "contacts-export.v2.fixture.json")
const CURRENT_BACKUP_FIXTURE = join(__dirname, "contacts-backup.fixture.json")

const ROW = '[data-testid="import-contact-row"]'
const SUBMIT = '[data-testid="import-contacts-submit"]'

// ── Harness ──────────────────────────────────────────────────────────

let activeProfile = "p1"
/** The live session's serial. A profile switch is a lock and an unlock, so it ends the session. */
let session = 1
function switchProfile(profileId: string): void {
	activeProfile = profileId
	session++
}
/** Each profile's registered senders, as the account-state port reports them back. */
const registered = new Map<string, Set<string>>()
const sendersOf = (profileId: string) => registered.get(profileId) ?? registered.set(profileId, new Set()).get(profileId)!
const accountState = {
	addSender: vi.fn(async (_networkId: string, address: string) => {
		sendersOf(activeProfile).add(address.toLowerCase())
		return address
	}),
	getSendersAcrossActiveNetworks: vi.fn(async () => [...sendersOf(activeProfile)]),
}

async function startWallet() {
	const api = new FakeBrowserApi()
	api.reset()
	const deletion = new ProfileDeletionState()
	const isFenceLive = (fence: RunFence) =>
		fence.session === session && fence.profileId === activeProfile && deletion.isCurrent(fence.profileId, fence.epoch)
	const profile = {
		getActiveProfile: async () => ({ id: activeProfile, name: activeProfile, type: "password" }),
		getDeletionState: () => deletion,
		captureExecutionFence: async () => ({ profileId: activeProfile, epoch: deletion.capture(activeProfile), session }),
		captureRunFence: async (): Promise<RunFence> => ({
			profileId: activeProfile,
			epoch: deletion.capture(activeProfile),
			session,
			incarnation: "w1",
		}),
		assertRunFence: async (fence: RunFence) => {
			if (fence?.incarnation !== "w1" || !isFenceLive(fence)) throw new SessionEndedError()
		},
		isFenceLive,
	}
	boundary.profile = profile
	const services = new ServiceCollection()
	services.add(svc(PROFILE_SERVICE_NAME, profile))
	const contacts = new ContactService(new LoggerStore(new ConfigStore()), api)
	services.add(contacts)
	await services.start()
	boundary.service = contacts
	return { api, contacts, profile }
}

type ProfileStub = Awaited<ReturnType<typeof startWallet>>["profile"]

const mounted: VueWrapper[] = []

/** The Contacts page: its import/export composable, and the import popup as the popup manager shows it. */
function openContactsPage(contacts: ContactService) {
	const list = ref<Contact[]>([])
	const io = useContactImportExport({ contacts: list, contactService: contacts as never, accountStateService: accountState as never })
	const popup: VueWrapper = mount(ImportContactsPopup, {
		props: { show: false, onOnClose: () => popup.setProps({ show: false }) },
		global: { stubs: STUBS },
	})
	mounted.push(popup)
	return { io, popup, list }
}
type ContactsPage = ReturnType<typeof openContactsPage>

/** Picks `content` and waits until the popup shows its rows. `done` settles when the import ends. */
async function pick(page: ContactsPage, content: string): Promise<{ done: Promise<void> }> {
	boundary.file = { size: new TextEncoder().encode(content).length, text: async () => content }
	boundary.opened.length = 0
	const done = page.io.importContacts()
	await vi.waitFor(() => expect(boundary.opened).toEqual(["import_contacts"]))
	await page.popup.setProps({ show: true })
	await flushPromises()
	return { done }
}
const fileOf = (contacts: unknown[]) => JSON.stringify({ version: 2, contacts })

function rowOf(popup: VueWrapper, name: string) {
	const row = popup.findAll(ROW).find((r) => r.attributes("data-contact-name") === name)
	if (!row) throw new Error(`no row for ${name}`)
	return row
}
const press = (popup: VueWrapper, name: string) => rowOf(popup, name).find('[data-testid="import-contact-target"]').trigger("click")
const shown = (popup: VueWrapper) =>
	popup.findAll(ROW).map((r) => ({
		name: r.attributes("data-contact-name"),
		kind: r.attributes("data-row-kind"),
		selected: r.attributes("data-selected") === "true",
	}))
function senderLine(popup: VueWrapper): string | null {
	const line = popup.find('[data-testid="import-contacts-senders"]')
	return line.exists() ? line.text().replace(/\s+/g, " ").trim() : null
}

/** Opens a row in the edit form through its own button and writes back what that form saves in import
 *  mode (EditContactPopup: the staged row with the trimmed name and lowercase address, `updated`). */
async function saveEdit(popup: VueWrapper, name: string, change: { name?: string; address?: string }) {
	await rowOf(popup, name).find('[data-testid="import-contact-edit"]').trigger("click")
	const cache = useCacheStore() as unknown as { importContact: Record<string, unknown> }
	cache.importContact = { ...cache.importContact, ...change, updated: true }
	await flushPromises()
}

async function confirm(page: ContactsPage, done: Promise<void>): Promise<string | undefined> {
	await page.popup.find(SUBMIT).trigger("click")
	await done
	await flushPromises()
	return boundary.toasts.at(-1)?.label
}

async function book(contacts: ContactService): Promise<Record<string, string>> {
	return Object.fromEntries((await contacts.getContacts()).map((c) => [c.name, c.address]))
}

/** A book as a released wallet can hold it: a 25-character name, letters of other scripts, a name
 *  stored with outer spaces by an older import, and an address stored before addresses were saved
 *  lowercase. Fixed ids, so what the export and the backup write is fixed too. */
async function seedReleasedBook(api: FakeBrowserApi): Promise<void> {
	const rows = [
		{ id: "c1", name: "Bartholomew Featherstones", address: ADDR.a, abbr: "BF" },
		{ id: "c2", name: "Zoë Ångström", address: ADDR.b, abbr: "ZÅ" },
		{ id: "c3", name: " Tom Becker ", address: ADDR.c, abbr: "TB" },
		{ id: "c4", name: "Marco Rossi", address: upper(ADDR.d), abbr: "MR" },
	]
	for (const row of rows) {
		await api.storage.local.set({ [`${CONTACT_STORAGE_ROOT}@${row.id}`]: JSON.stringify({ ...row, profileId: "p1" }) })
	}
	sendersOf("p1").add(ADDR.a)
	sendersOf("p1").add(ADDR.d)
}

/** The current code's output must equal the committed fixture; on request it writes a missing one. */
function expectFixture(path: string, written: string): void {
	if (process.env.NULO_WRITE_CONTACT_FIXTURES === "1" && !existsSync(path)) writeFileSync(path, written, { flag: "wx" })
	expect(JSON.parse(written)).toEqual(JSON.parse(readFileSync(path, "utf8")))
}

beforeEach(() => {
	vi.clearAllMocks()
	Object.assign(useCacheStore(), { importContacts: [], importContact: null, importPromise: null })
	activeProfile = "p1"
	session = 1
	registered.clear()
	boundary.file = null
	boundary.downloads.length = 0
	boundary.toasts.length = 0
	boundary.opened.length = 0
})

afterEach(() => {
	for (const popup of mounted.splice(0)) popup.unmount()
})

// ── The screen is the contract ───────────────────────────────────────

describe("import composition — what the screen showed chosen is what is written", () => {
	test("toggles, an edit, a deselected row and pressed rows that can't be imported: the book and the senders follow the screen", async () => {
		const { contacts } = await startWallet()
		for (const [name, address] of [
			["Alice", ADDR.a],
			["Bob", ADDR.b],
			["Carol", ADDR.c],
			["Dave", ADDR.d],
		]) {
			await contacts.addContact(name, address)
		}
		const aliceId = (await contacts.getContacts()).find((c) => c.name === "Alice")?.id
		const page = openContactsPage(contacts)

		const { done } = await pick(
			page,
			fileOf([
				{ name: "Alice", address: ADDR.e, isSender: true },
				{ name: "Bobby", address: ADDR.b },
				{ name: "Erin", address: ADDR.f, isSender: true },
				{ name: "Gina", address: ADDR.g },
				{ name: "Hugo", address: ADDR.h, isSender: true },
				{ name: "Carol", address: ADDR.c },
				{ name: "Ivan", address: OFF_CURVE },
				{ name: "Dave", address: ADDR.a },
			]),
		)
		expect(shown(page.popup)).toEqual([
			{ name: "Alice", kind: "address-change", selected: false },
			{ name: "Bobby", kind: "name-change", selected: false },
			{ name: "Erin", kind: "new", selected: true },
			{ name: "Gina", kind: "new", selected: true },
			{ name: "Hugo", kind: "new", selected: true },
			{ name: "Carol", kind: "unchanged", selected: false },
			{ name: "Ivan", kind: "invalid", selected: false },
			{ name: "Dave", kind: "conflict", selected: false },
		])

		for (const name of ["Alice", "Alice", "Alice", "Bobby", "Bobby", "Hugo", "Ivan", "Dave"]) await press(page.popup, name)
		await saveEdit(page.popup, "Gina", { name: "Gwen" })
		expect(
			shown(page.popup)
				.filter((r) => r.selected)
				.map((r) => r.name),
		).toEqual(["Alice", "Erin", "Gwen"])
		expect(senderLine(page.popup)).toBe("2 senders will be registered on Testnet.")

		expect(await confirm(page, done)).toBe("Contacts imported · 2 senders registered")
		expect(await book(contacts)).toEqual({ Alice: ADDR.e, Bob: ADDR.b, Carol: ADDR.c, Dave: ADDR.d, Erin: ADDR.f, Gwen: ADDR.g })
		expect((await contacts.getContacts()).find((c) => c.name === "Alice")?.id).toBe(aliceId)
		expect([...sendersOf("p1")].sort()).toEqual([ADDR.e, ADDR.f].sort())
	})

	test("a book changed under the open popup: rows whose saved contact moved are refused, sender included; the rest are written", async () => {
		const { contacts } = await startWallet()
		await contacts.addContact("Alice", ADDR.a)
		await contacts.addContact("Bob", ADDR.b)
		const saved = await contacts.getContacts()
		const named = (name: string) => saved.find((c) => c.name === name) as Contact
		const [alice, bob] = [named("Alice"), named("Bob")]
		const page = openContactsPage(contacts)

		const { done } = await pick(
			page,
			fileOf([
				{ name: "Alice", address: ADDR.d, isSender: true },
				{ name: "Bob", address: ADDR.e },
				{ name: "Dora", address: ADDR.g, isSender: true },
				{ name: "Erin", address: ADDR.h },
			]),
		)
		await press(page.popup, "Alice")
		await press(page.popup, "Bob")
		expect(senderLine(page.popup)).toBe("2 senders will be registered on Testnet.")

		// Another window: Alice is renamed (her row would now add a new contact), Bob's address changes
		// (his row is still his address change, but not from the address it showed), and a Dora is saved.
		await contacts.updateContact(alice.id, "Alicia")
		await contacts.updateContact(bob.id, undefined, ADDR.f)
		await contacts.addContact("Dora", ADDR.i)
		await flushPromises()
		expect(senderLine(page.popup)).toBeNull()

		expect(await confirm(page, done)).toBe("Import ended with errors")
		expect(await book(contacts)).toEqual({ Alicia: ADDR.a, Bob: ADDR.f, Dora: ADDR.i, Erin: ADDR.h })
		expect(accountState.addSender).not.toHaveBeenCalled()
	})
})

describe("import composition — a profile switch mid-import", () => {
	const threeNew = fileOf([
		{ name: "Ana", address: ADDR.a, isSender: true },
		{ name: "Ben", address: ADDR.b },
		{ name: "Cleo", address: ADDR.c },
	])
	/** Every stored contact's name by profile, read from storage itself rather than through a fence. */
	async function namesByProfile(api: FakeBrowserApi): Promise<Record<string, string[]>> {
		const out: Record<string, string[]> = {}
		for (const [key, raw] of Object.entries(await api.storage.local.get(null))) {
			if (!key.startsWith(`${CONTACT_STORAGE_ROOT}@`)) continue
			const row = JSON.parse(raw as string) as Contact
			out[row.profileId] = [...(out[row.profileId] ?? []), row.name]
		}
		return out
	}

	test("a switch after the first row writes nothing more, to either profile, and the toast reports it", async () => {
		const { api, contacts } = await startWallet()
		const page = openContactsPage(contacts)
		accountState.addSender.mockImplementationOnce(async (_networkId: string, address: string) => {
			sendersOf(activeProfile).add(address.toLowerCase())
			switchProfile("p2")
			return address
		})

		const { done } = await pick(page, threeNew)
		expect(await confirm(page, done)).toBe("Import incomplete · 1 contact written")
		expect(await namesByProfile(api)).toEqual({ p1: ["Ana"] })
		expect(accountState.addSender).toHaveBeenCalledTimes(1)
		expect([...sendersOf("p1")]).toEqual([ADDR.a])
		expect(sendersOf("p2").size).toBe(0)
	})

	test("control: the same file without a switch writes every row to the profile it was shown in", async () => {
		const { api, contacts } = await startWallet()
		const page = openContactsPage(contacts)

		const { done } = await pick(page, threeNew)
		expect(await confirm(page, done)).toBe("Contacts imported · 1 sender registered")
		expect(await namesByProfile(api)).toEqual({ p1: ["Ana", "Ben", "Cleo"] })
		expect([...sendersOf("p1")]).toEqual([ADDR.a])
	})
})

describe("import composition — one name, whatever its case, spacing or invisible characters", () => {
	test("every row shows the name it writes: matched rows keep the saved spelling, a rename the file's, rows that can't be imported write nothing", async () => {
		const { api, contacts } = await startWallet()
		for (const [name, address] of [
			["Alice", ADDR.a],
			["Dave", ADDR.d],
			["Erin", ADDR.e],
			["Gus", ADDR.g],
		]) {
			await contacts.addContact(name, address)
		}
		// Saved before names were cleaned on save: the rows show, and write, the name as it is stored now.
		for (const [id, name, address] of [
			["legacy-bob", " Bob Stone ", ADDR.b],
			["legacy-carol", "Car\u3164ol", ADDR.c],
		]) {
			await api.storage.local.set({
				[`${CONTACT_STORAGE_ROOT}@${id}`]: JSON.stringify({ id, profileId: "p1", name, address, abbr: "" }),
			})
		}
		const aliceId = (await contacts.getContacts()).find((c) => c.name === "Alice")?.id
		const page = openContactsPage(contacts)

		const { done } = await pick(
			page,
			fileOf([
				{ name: "ALICE", address: ADDR.a },
				{ name: "Bob   Stone ", address: ADDR.f },
				{ name: "Car\u3164ol\u200B", address: ADDR.c },
				{ name: "dave\u3164", address: ADDR.h },
				{ name: "alice", address: ADDR.i },
				{ name: "\u0410lice", address: ADDR.j },
				{ name: "Erin  Ray", address: ADDR.e },
				{ name: "GUS", address: ADDR.d },
				{ name: "Hal", address: OFF_CURVE },
			]),
		)
		const rows = shown(page.popup)
		expect(rows).toEqual([
			{ name: "Bob Stone", kind: "address-change", selected: false },
			{ name: "Dave", kind: "address-change", selected: false },
			{ name: "Erin Ray", kind: "name-change", selected: false },
			{ name: "\u0410lice", kind: "new", selected: true },
			{ name: "Alice", kind: "unchanged", selected: false },
			{ name: "Carol", kind: "unchanged", selected: false },
			{ name: "GUS", kind: "conflict", selected: false },
			{ name: "Hal", kind: "invalid", selected: false },
		])
		for (const name of ["Bob Stone", "Dave", "Erin Ray", "Alice", "Carol", "GUS", "Hal"]) await press(page.popup, name)

		expect(await confirm(page, done)).toBe("Import completed successfully")
		const saved = await book(contacts)
		expect(saved).toEqual({
			Alice: ADDR.a,
			"Bob Stone": ADDR.f,
			Carol: ADDR.c,
			Dave: ADDR.h,
			"Erin Ray": ADDR.e,
			Gus: ADDR.g,
			"\u0410lice": ADDR.j,
		})
		const rowAddress: Record<string, string> = {
			Alice: ADDR.a,
			"Bob Stone": ADDR.f,
			Carol: ADDR.c,
			Dave: ADDR.h,
			"\u0410lice": ADDR.j,
			"Erin Ray": ADDR.e,
			GUS: ADDR.d,
			Hal: OFF_CURVE,
		}
		for (const row of rows) {
			const written = Object.entries(saved).find(([, address]) => address === rowAddress[row.name ?? ""])?.[0]
			expect(written, row.kind).toBe(row.kind === "conflict" || row.kind === "invalid" ? undefined : row.name)
		}
		expect((await contacts.getContacts()).find((c) => c.name === "Alice")?.id).toBe(aliceId)
	})
})

// ── Round trips ──────────────────────────────────────────────────────

describe("import composition — the released contacts file", () => {
	test("export writes the released file; into the same book nothing changes, into an empty book it comes back with its senders, and a second time nothing changes", async () => {
		const { api, contacts } = await startWallet()
		await seedReleasedBook(api)
		const page = openContactsPage(contacts)
		page.list.value = await contacts.getContacts()

		await page.io.exportContacts()
		expect(boundary.downloads).toHaveLength(1)
		expectFixture(CURRENT_EXPORT_FIXTURE, boundary.downloads[0])
		const released = readFileSync(CURRENT_EXPORT_FIXTURE, "utf8")

		const before = await api.storage.local.get(null)
		let { done } = await pick(page, released)
		expect(shown(page.popup).every((r) => r.kind === "unchanged" && !r.selected)).toBe(true)
		expect(shown(page.popup)).toHaveLength(4)
		expect(await confirm(page, done)).toBe("No contacts selected for import")
		expect(await api.storage.local.get(null)).toEqual(before)

		switchProfile("p2")
		;({ done } = await pick(page, released))
		expect(shown(page.popup).every((r) => r.kind === "new" && r.selected)).toBe(true)
		expect(senderLine(page.popup)).toBe("2 senders will be registered on Testnet.")
		expect(await confirm(page, done)).toBe("Contacts imported · 2 senders registered")
		expect(await book(contacts)).toEqual({
			"Bartholomew Featherstones": ADDR.a,
			"Zoë Ångström": ADDR.b,
			"Tom Becker": ADDR.c,
			"Marco Rossi": ADDR.d,
		})
		expect([...sendersOf("p2")].sort()).toEqual([ADDR.a, ADDR.d].sort())

		const imported = await api.storage.local.get(null)
		;({ done } = await pick(page, released))
		expect(shown(page.popup).every((r) => r.kind === "unchanged" && !r.selected)).toBe(true)
		expect(await confirm(page, done)).toBe("No contacts selected for import")
		expect(await api.storage.local.get(null)).toEqual(imported)
		expect(accountState.addSender).toHaveBeenCalledTimes(2)
	})
})

describe("import composition — the released full backup", () => {
	test("a full backup's contacts, as the released backup writes them, restore into an empty profile with names trimmed and kept to 25", async () => {
		const { api, contacts } = await startWallet()
		await seedReleasedBook(api)
		const assembled = await assembleFullBackup(
			{ [COMPAT_EPOCH_FIELD]: CURRENT_COMPAT_EPOCH, [BACKUP_SCHEMA_VERSION_FIELD]: CURRENT_BACKUP_SCHEMA_VERSION },
			[{ name: CONTACT_SERVICE_NAME, backup: () => contacts.backup() }],
		)
		expectFixture(CURRENT_BACKUP_FIXTURE, assembled.pretty)

		const validated = await validateAndMigrateBackup(JSON.parse(readFileSync(CURRENT_BACKUP_FIXTURE, "utf8")))
		if (validated.kind !== "ok") throw new Error(`the released backup was rejected: ${validated.message}`)
		switchProfile("p2")
		normalizeAllIds(validated.data, "profileId", "p2")
		const errors: unknown[] = []
		await restoreServiceSlices(
			validated.data,
			[{ name: CONTACT_SERVICE_NAME, client: { restore: (rows) => contacts.restore(rows as Contact[]), disconnect() {} } }],
			"p2",
			{
				fillError() {},
				setStatus() {},
				setStage() {},
				appendErrors() {},
				recordRestoreErrors: (_service, restored) => {
					errors.push(...(restored as Array<{ restoreError?: unknown }>).filter((r) => r.restoreError))
					return []
				},
			},
		)

		expect(errors).toEqual([])
		expect(await book(contacts)).toEqual({
			"Bartholomew Featherstones": ADDR.a,
			"Zoë Ångström": ADDR.b,
			"Tom Becker": ADDR.c,
			"Marco Rossi": upper(ADDR.d),
		})
	})
})
