/**
 * GENERATED by scripts/gen-tokens.ts from src/token-contract.ts — DO NOT EDIT.
 * Run `bun run gen:tokens` after changing the contract; tokens.drift.test.ts fails CI on
 * divergence. Members are CSS-variable NAMES; use cssVar() to wrap for inline styles.
 */

export const surfaces = {
	appBg: "--app-bg",
	cardBg: "--card-bg",
	tooltipBg: "--tooltip-bg",
	dropdownBg: "--dropdown-bg",
	nuloSurface: "--nulo-surface",
	nuloSurfaceLow: "--nulo-surface-low",
	nuloSurfaceHigh: "--nulo-surface-high",
	nuloSurfaceHighest: "--nulo-surface-highest",
} as const

export const brand = {
	accent: "--nulo-accent",
	secondary: "--nulo-secondary",
	outline: "--nulo-outline",
	border: "--nulo-border",
} as const

export const text = {
	primary: "--txt-primary",
	secondary: "--txt-secondary",
	body: "--txt-body",
	tertiary: "--txt-tertiary",
	support: "--txt-support",
	white: "--txt-white",
	inverse: "--txt-inverse",
} as const

export const borders = {
	default: "--border",
	hovered: "--border-hovered",
	hairlineSoft: "--hairline-soft",
	hairlineStrong: "--hairline-strong",
} as const

export const scrims = {
	popup: "--scrim-popup",
	sheet: "--scrim-sheet",
	loader: "--scrim-loader",
	barrier: "--scrim-barrier",
} as const

export const colors = {
	white: "--white",
	black: "--black",
	blue: "--blue",
	green: "--green",
	mint: "--mint",
	neutralMint: "--neutral-mint",
	orange: "--orange",
	yellow: "--yellow",
	red: "--red",
	purple: "--purple",
	gray: "--gray",
	sand: "--sand",
} as const

export const fonts = {
	headline: "--font-headline",
	body: "--font-body",
	mono: "--font-mono",
} as const

export const easings = {
	bezier: "--bezier",
} as const

export const layout = {
	baseWidth: "--base-width",
	baseHeight: "--base-height",
	navClearance: "--nav-clearance",
} as const

export const fontSizes = [8, 10, 11, 12, 13, 14, 15, 16, 18, 20, 24, 26, 28, 32, 36, 38, 40] as const

export const fontWeights = [400, 500, 600, 700] as const

export const lineHeights = {
	100: 1,
	110: 1.1,
	120: 1.2,
	130: 1.3,
	140: 1.4,
	150: 1.5,
	160: 1.6,
	180: 1.8,
} as const

export const durations = {
	short: "150ms",
	medium: "200ms",
	long: "300ms",
} as const

export const cssVar = (name: string, fallback?: string): string => (fallback === undefined ? `var(${name})` : `var(${name}, ${fallback})`)

export type SurfaceToken = (typeof surfaces)[keyof typeof surfaces]
export type BrandToken = (typeof brand)[keyof typeof brand]
export type TextToken = (typeof text)[keyof typeof text]
export type ColorToken = (typeof colors)[keyof typeof colors]
export type FontToken = (typeof fonts)[keyof typeof fonts]
export type FontSize = (typeof fontSizes)[number]
export type FontWeight = (typeof fontWeights)[number]
export type LineHeight = keyof typeof lineHeights
